-- =====================================================
-- Create All Missing Aggregation Metrics
-- =====================================================
-- Generated from display_metrics mapping
-- Creates aggregation_metrics and aggregation_metrics_periods entries
--
-- Created: 2025-10-22
-- =====================================================

BEGIN;

-- =====================================================
-- PART 1: Create Aggregation Metrics
-- =====================================================

-- BASELINE_COMPARISON Pattern (2 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_ALCOHOLIC_DRINKS_VS_BASELINE', 'alcoholic_drinks_vs_baseline', 'Alcoholic Drinks vs. Baseline', 'Aggregated alcoholic drinks vs. baseline', 'count', true),
('AGG_CIGARETTES_VS_BASELINE', 'cigarettes_vs_baseline', 'Cigarettes vs. Baseline', 'Aggregated cigarettes vs. baseline', 'count', true);

-- COMPLIANCE Pattern (6 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_EVENING_ROUTINE_ADHERENCE', 'evening_routine_adherence', 'Evening Routine Adherence', 'Aggregated evening routine adherence', 'percentage', true),
('AGG_MEDICATION_ADHERENCE', 'medication_adherence', 'Medication Adherence', 'Aggregated medication adherence', 'percentage', true),
('AGG_PEPTIDE_ADHERENCE', 'peptide_adherence', 'Peptide Adherence', 'Aggregated peptide adherence', 'percentage', true),
('AGG_SKINCARE_ROUTINE_ADHERENCE', 'skincare_routine_adherence', 'Skincare Routine Adherence', 'Aggregated skincare routine adherence', 'percentage', true),
('AGG_SUPPLEMENT_ADHERENCE', 'supplement_adherence', 'Supplement Adherence', 'Aggregated supplement adherence', 'percentage', true),
('AGG_SLEEP_ROUTINE_ADHERENCE', 'sleep_routine_adherence', 'Sleep Routine Adherence', 'Aggregated sleep routine adherence', 'percentage', true);

-- CONSISTENCY Pattern (2 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_SLEEP_TIME_CONSISTENCY', 'sleep_time_consistency', 'Sleep Time Consistency', 'Aggregated sleep time consistency', 'hours', true),
('AGG_WAKE_TIME_CONSISTENCY', 'wake_time_consistency', 'Wake Time Consistency', 'Aggregated wake time consistency', 'minutes', true);

-- CURRENT_VALUE Pattern (53 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_SOCIAL_INTERACTION', 'social_interaction', 'Social Interaction', 'Aggregated social interaction', 'count', true),
('AGG_BMI', 'bmi', 'BMI (Calculated)', 'Aggregated bmi (calculated)', 'count', true),
('AGG_BREAST_MRI_COMPLIANCE_STATUS', 'breast_mri_compliance_status', 'Breast MRI Compliance Status', 'Aggregated breast mri compliance status', 'percentage', true),
('AGG_CERVICAL_SCREENING_COMPLIANCE_STATUS', 'cervical_screening_compliance_status', 'Cervical Screening Compliance Status', 'Aggregated cervical screening compliance status', 'percentage', true),
('AGG_CIGARETTES', 'cigarettes', 'Cigarettes', 'Aggregated cigarettes', 'count', true),
('AGG_COLONOSCOPY_COMPLIANCE_STATUS', 'colonoscopy_compliance_status', 'Colonoscopy Compliance Status', 'Aggregated colonoscopy compliance status', 'percentage', true),
('AGG_DENTAL_COMPLIANCE_STATUS', 'dental_compliance_status', 'Dental Compliance Status', 'Aggregated dental compliance status', 'percentage', true),
('AGG_DIGITAL_SHUTOFF_BUFFER', 'digital_shutoff_buffer', 'Digital Shutoff Buffer', 'Aggregated digital shutoff buffer', 'hours', true),
('AGG_MAMMOGRAM_COMPLIANCE_STATUS', 'mammogram_compliance_status', 'Mammogram Compliance Status', 'Aggregated mammogram compliance status', 'percentage', true),
('AGG_MONTHS_SINCE_LAST_BREAST_MRI', 'months_since_last_breast_mri', 'Months Since Last Breast MRI', 'Aggregated months since last breast mri', 'months', true),
('AGG_MONTHS_SINCE_LAST_DENTAL_EXAM', 'months_since_last_dental_exam', 'Months Since Last Dental Exam', 'Aggregated months since last dental exam', 'months', true),
('AGG_MONTHS_SINCE_LAST_MAMMOGRAM', 'months_since_last_mammogram', 'Months Since Last Mammogram', 'Aggregated months since last mammogram', 'months', true),
('AGG_MONTHS_SINCE_LAST_SKIN_CHECK', 'months_since_last_skin_check', 'Months Since Last Skin Check', 'Aggregated months since last skin check', 'months', true),
('AGG_MONTHS_SINCE_LAST_VISION_CHECK', 'months_since_last_vision_check', 'Months Since Last Vision Check', 'Aggregated months since last vision check', 'months', true),
('AGG_MORNING_SUNSCREEN_APPLICATIONS', 'morning_sunscreen_applications', 'Morning Sunscreen Applications', 'Aggregated morning sunscreen applications', 'count', true),
('AGG_PHYSICAL_EXAM_COMPLIANCE_STATUS', 'physical_exam_compliance_status', 'Physical Exam Compliance Status', 'Aggregated physical exam compliance status', 'percentage', true),
('AGG_PSA_TEST_COMPLIANCE_STATUS', 'psa_test_compliance_status', 'PSA Test Compliance Status', 'Aggregated psa test compliance status', 'percentage', true),
('AGG_SKIN_CHECK_COMPLIANCE_STATUS', 'skin_check_compliance_status', 'Skin Check Compliance Status', 'Aggregated skin check compliance status', 'percentage', true),
('AGG_SUNSCREEN_APPLICATIONS', 'sunscreen_applications', 'Sunscreen Applications', 'Aggregated sunscreen applications', 'count', true),
('AGG_SUNSCREEN_COMPLIANCE_EVENTS', 'sunscreen_compliance_events', 'Sunscreen Compliance Events', 'Aggregated sunscreen compliance events', 'percentage', true),
('AGG_SUNSCREEN_COMPLIANCE_RATE', 'sunscreen_compliance_rate', 'Sunscreen Compliance Rate', 'Aggregated sunscreen compliance rate', 'percentage', true),
('AGG_USER_AGE', 'user_age', 'User Age', 'Aggregated user age', 'count', true),
('AGG_VISION_CHECK_COMPLIANCE_STATUS', 'vision_check_compliance_status', 'Vision Check Compliance Status', 'Aggregated vision check compliance status', 'percentage', true),
('AGG_YEARS_SINCE_LAST_COLONOSCOPY', 'years_since_last_colonoscopy', 'Years Since Last Colonoscopy', 'Aggregated years since last colonoscopy', 'months', true),
('AGG_YEARS_SINCE_LAST_HPV_SCREENING', 'years_since_last_hpv_screening', 'Years Since Last HPV Screening', 'Aggregated years since last hpv screening', 'months', true),
('AGG_YEARS_SINCE_LAST_PAP_TEST', 'years_since_last_pap_test', 'Years Since Last Pap Test', 'Aggregated years since last pap test', 'months', true),
('AGG_YEARS_SINCE_LAST_PHYSICAL', 'years_since_last_physical', 'Years Since Last Physical', 'Aggregated years since last physical', 'months', true),
('AGG_YEARS_SINCE_LAST_PSA_TEST', 'years_since_last_psa_test', 'Years Since Last PSA Test', 'Aggregated years since last psa test', 'months', true),
('AGG_BREAKFAST', 'breakfast', 'Breakfast', 'Aggregated breakfast', 'count', true),
('AGG_DINNER', 'dinner', 'Dinner', 'Aggregated dinner', 'count', true),
('AGG_FAT_SOURCES', 'fat_sources', 'Fat Sources', 'Aggregated fat sources', 'count', true),
('AGG_FIBER_SOURCES', 'fiber_sources', 'Fiber Sources', 'Aggregated fiber sources', 'count', true),
('AGG_FIRST_MEAL_DELAY', 'first_meal_delay', 'First Meal Delay', 'Aggregated first meal delay', 'count', true),
('AGG_FRUIT_SOURCES', 'fruit_sources', 'Fruit Sources', 'Aggregated fruit sources', 'count', true),
('AGG_HEALTHY_FAT_USAGE', 'healthy_fat_usage', 'Healthy Fat Usage', 'Aggregated healthy fat usage', 'count', true),
('AGG_LAST_LARGE_MEAL_BUFFER', 'last_large_meal_buffer', 'Last Large Meal Buffer', 'Aggregated last large meal buffer', 'hours', true),
('AGG_LAST_LARGE_MEAL_TIME', 'last_large_meal_time', 'Last Large Meal Time', 'Aggregated last large meal time', 'minutes', true),
('AGG_LAST_MEAL_BUFFER', 'last_meal_buffer', 'Last Meal Buffer', 'Aggregated last meal buffer', 'hours', true),
('AGG_LEGUME_SOURCES', 'legume_sources', 'Legume Sources', 'Aggregated legume sources', 'count', true),
('AGG_LUNCH', 'lunch', 'Lunch', 'Aggregated lunch', 'count', true),
('AGG_MINDFUL_EATING', 'mindful_eating', 'Mindful Eating: Breakfast', 'Aggregated mindful eating: breakfast', 'count', true),
('AGG_PLANT_BASED_MEAL', 'plant_based_meal', 'Plant Based Meal', 'Aggregated plant based meal', 'count', true),
('AGG_UNHEALTHY_FAT_USAGE', 'unhealthy_fat_usage', 'Unhealthy Fat Usage', 'Aggregated unhealthy fat usage', 'count', true),
('AGG_VEGETABLE_SOURCES', 'vegetable_sources', 'Vegetable Sources', 'Aggregated vegetable sources', 'count', true),
('AGG_WHOLE_GRAIN_SOURCES', 'whole_grain_sources', 'Whole Grain Sources', 'Aggregated whole grain sources', 'count', true),
('AGG_CAFFEINE_SOURCES', 'caffeine_sources', 'Caffeine Sources', 'Aggregated caffeine sources', 'count', true),
('AGG_ZONE_2_CARDIO_SESSION', 'zone_2_cardio_session', 'Zone 2 Cardio Session', 'Aggregated zone 2 cardio session', 'count', true),
('AGG_LAST_ALCOHOLIC_DRINK_TIME', 'last_alcoholic_drink_time', 'Last Alcoholic Drink Time', 'Aggregated last alcoholic drink time', 'minutes', true),
('AGG_LAST_DIGITAL_DEVICE_TIME_USAGE', 'last_digital_device_time_usage', 'Last Digital Device Time Usage', 'Aggregated last digital device time usage', 'minutes', true),
('AGG_SLEEP_EFFICIENCY', 'sleep_efficiency', 'Sleep Efficiency', 'Aggregated sleep efficiency', 'count', true),
('AGG_SLEEP_LATENCY', 'sleep_latency', 'Sleep Latency', 'Aggregated sleep latency', 'hours', true),
('AGG_TOTAL_SLEEP_WINDOW', 'total_sleep_window', 'Total Sleep Window', 'Aggregated total sleep window', 'count', true),
('AGG_WEARABLE_USAGE', 'wearable_usage', 'Wearable Usage', 'Aggregated wearable usage', 'count', true);

-- DURATION Pattern (32 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_BRAIN_TRAINING_DURATION', 'brain_training_duration', 'Brain Training Duration', 'Aggregated brain training duration', 'minutes', true),
('AGG_EARLY_MORNING_LIGHT_EXPOSURE_DURATION', 'early_morning_light_exposure_duration', 'Early Morning Light Exposure Duration', 'Aggregated early morning light exposure duration', 'minutes', true),
('AGG_SUNLIGHT_EXPOSURE_DURATION', 'sunlight_exposure_duration', 'Sunlight Exposure Duration', 'Aggregated sunlight exposure duration', 'minutes', true),
('AGG_MINDFULNESS_DURATION', 'mindfulness_duration', 'Mindfulness Duration', 'Aggregated mindfulness duration', 'minutes', true),
('AGG_MORNING_OUTDOOR_TIME_DURATION', 'morning_outdoor_time_duration', 'Morning Outdoor Time Duration', 'Aggregated morning outdoor time duration', 'minutes', true),
('AGG_OUTDOOR_TIME_DURATION', 'outdoor_time_duration', 'Outdoor Time Duration', 'Aggregated outdoor time duration', 'minutes', true),
('AGG_SCREEN_TIME_DURATION', 'screen_time_duration', 'Screen Time Duration', 'Aggregated screen time duration', 'minutes', true),
('AGG_STRESS_MANAGEMENT_DURATION', 'stress_management_duration', 'Stress Management Duration', 'Aggregated stress management duration', 'minutes', true),
('AGG_WALKING_DURATION', 'walking_duration', 'Walking Duration', 'Aggregated walking duration', 'minutes', true),
('AGG_EATING_WINDOW_DURATION', 'eating_window_duration', 'Eating Window Duration', 'Aggregated eating window duration', 'minutes', true),
('AGG_HIIT_DURATION', 'hiit_duration', 'HIIT Duration', 'Aggregated hiit duration', 'minutes', true),
('AGG_MOBILITY_DURATION', 'mobility_duration', 'Mobility Duration', 'Aggregated mobility duration', 'minutes', true),
('AGG_POST_MEAL_ACTIVITY_DURATION', 'post_meal_activity_duration', 'Post Meal Activity Duration', 'Aggregated post meal activity duration', 'minutes', true),
('AGG_STRENGTH_TRAINING_DURATION', 'strength_training_duration', 'Strength Training Duration', 'Aggregated strength training duration', 'minutes', true),
('AGG_ZONE_2_CARDIO_DURATION', 'zone_2_cardio_duration', 'Zone 2 Cardio Duration', 'Aggregated zone 2 cardio duration', 'minutes', true),
('AGG_AWAKE_DURATION', 'awake_duration', 'Awake Duration', 'Aggregated awake duration', 'minutes', true),
('AGG_AWAKE_PERIOD_DURATION', 'awake_period_duration', 'Awake Period Duration', 'Aggregated awake period duration', 'minutes', true),
('AGG_CORE_SLEEP_DURATION', 'core_sleep_duration', 'Core Sleep Duration', 'Aggregated core sleep duration', 'hours', true),
('AGG_CORE_SLEEP_PERIOD_DURATION', 'core_sleep_period_duration', 'Core Sleep Period Duration', 'Aggregated core sleep period duration', 'hours', true),
('AGG_DEEP_SLEEP_DURATION', 'deep_sleep_duration', 'Deep Sleep Duration', 'Aggregated deep sleep duration', 'hours', true),
('AGG_DEEP_SLEEP_PERIOD_DURATION', 'deep_sleep_period_duration', 'Deep Sleep Period Duration', 'Aggregated deep sleep period duration', 'hours', true),
('AGG_PERIOD_AWAKE_DURATION', 'period_awake_duration', 'Period Awake Duration', 'Aggregated period awake duration', 'minutes', true),
('AGG_PERIOD_CORE_SLEEP_DURATION', 'period_core_sleep_duration', 'Period Core Sleep Duration', 'Aggregated period core sleep duration', 'hours', true),
('AGG_PERIOD_DEEP_SLEEP_DURATION', 'period_deep_sleep_duration', 'Period Deep Sleep Duration', 'Aggregated period deep sleep duration', 'hours', true),
('AGG_PERIOD_REM_SLEEP_DURATION', 'period_rem_sleep_duration', 'Period REM Sleep Duration', 'Aggregated period rem sleep duration', 'hours', true),
('AGG_REM_SLEEP_DURATION', 'rem_sleep_duration', 'REM Sleep Duration', 'Aggregated rem sleep duration', 'hours', true),
('AGG_REM_SLEEP_PERIOD_DURATION', 'rem_sleep_period_duration', 'REM Sleep Period Duration', 'Aggregated rem sleep period duration', 'hours', true),
('AGG_TIME_IN_BED_DURATION', 'time_in_bed_duration', 'Time In Bed Duration', 'Aggregated time in bed duration', 'minutes', true),
('AGG_TOTAL_SLEEP_DURATION', 'total_sleep_duration', 'Total Sleep Duration', 'Aggregated total sleep duration', 'hours', true),
('AGG_BREATHWORK_AND_MINDFULNESS_DURATION', 'breathwork_and_mindfulness_duration', 'Breathwork AND Mindfulness Duration', 'Aggregated breathwork and mindfulness duration', 'minutes', true),
('AGG_BREATHWORK_DURATION', 'breathwork_duration', 'Breathwork Duration', 'Aggregated breathwork duration', 'minutes', true),
('AGG_MEDITATION_DURATION', 'meditation_duration', 'Meditation Duration', 'Aggregated meditation duration', 'minutes', true);

-- GENERAL Pattern (53 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_ALCOHOLIC_DRINKS', 'alcoholic_drinks', 'Alcoholic Drinks', 'Aggregated alcoholic drinks', 'count', true),
('AGG_BODY_FAT_PERCENTAGE', 'body_fat_percentage', 'Body Fat Percentage', 'Aggregated body fat percentage', 'percentage', true),
('AGG_CURRENT_WEIGHT', 'current_weight', 'Current Weight', 'Aggregated current weight', 'count', true),
('AGG_DIASTOLIC_BLOOD_PRESSURE', 'diastolic_blood_pressure', 'Diastolic Blood Pressure', 'Aggregated diastolic blood pressure', 'count', true),
('AGG_HEIGHT', 'height', 'Height', 'Aggregated height', 'count', true),
('AGG_HIP_TO_WAIST_RATIO', 'hip_to_waist_ratio', 'Hip to Waist Ratio', 'Aggregated hip to waist ratio', 'ratio', true),
('AGG_LAST_CAFFEINE_CONSUMPTION_BUFFER', 'last_caffeine_consumption_buffer', 'Last Caffeine Consumption Buffer', 'Aggregated last caffeine consumption buffer', 'hours', true),
('AGG_LAST_CAFFEINE_CONSUMPTION_TIME', 'last_caffeine_consumption_time', 'Last Caffeine Consumption Time', 'Aggregated last caffeine consumption time', 'minutes', true),
('AGG_SYSTOLIC_BLOOD_PRESSURE', 'systolic_blood_pressure', 'Systolic Blood Pressure', 'Aggregated systolic blood pressure', 'count', true),
('AGG_ADDED_SUGAR_CONSUMED', 'added_sugar_consumed', 'Added Sugar Consumed', 'Aggregated added sugar consumed', 'count', true),
('AGG_CAFFEINE_CONSUMED', 'caffeine_consumed', 'Caffeine Consumed', 'Aggregated caffeine consumed', 'count', true),
('AGG_FIRST_MEAL_TIME', 'first_meal_time', 'First Meal Time', 'Aggregated first meal time', 'minutes', true),
('AGG_HEALTHY_FAT_RATIO', 'healthy_fat_ratio', 'Healthy Fat Ratio', 'Aggregated healthy fat ratio', 'ratio', true),
('AGG_HEALTHY_FAT_SWAPS', 'healthy_fat_swaps', 'Healthy Fat Swaps', 'Aggregated healthy fat swaps', 'count', true),
('AGG_LARGE_MEALS', 'large_meals', 'Large Meals', 'Aggregated large meals', 'count', true),
('AGG_LAST_MEAL_TIME', 'last_meal_time', 'Last Meal Time', 'Aggregated last meal time', 'minutes', true),
('AGG_MEALS', 'meals', 'Meals', 'Aggregated meals', 'count', true),
('AGG_MINDFUL_EATING_EPISODES', 'mindful_eating_episodes', 'Mindful Eating Episodes', 'Aggregated mindful eating episodes', 'count', true),
('AGG_PLANT_BASED_MEALS', 'plant_based_meals', 'Plant Based Meals: Breakfast', 'Aggregated plant based meals: breakfast', 'count', true),
('AGG_PLANTBASED_PROTEIN_PERCENTAGE', 'plantbased_protein_percentage', 'Plant-Based Protein Percentage', 'Aggregated plant-based protein percentage', 'percentage', true),
('AGG_PROCESS_MEAT', 'process_meat', 'Process Meat: Breakfast', 'Aggregated process meat: breakfast', 'count', true),
('AGG_PROCESSED_MEAT_SERVING', 'processed_meat_serving', 'Processed Meat Serving', 'Aggregated processed meat serving', 'count', true),
('AGG_PROTEIN_PER_KILOGRAM_BODY_WEIGHT', 'protein_per_kilogram_body_weight', 'Protein per Kilogram Body Weight', 'Aggregated protein per kilogram body weight', 'count', true),
('AGG_SATURATED_FAT_PERCENTAGE', 'saturated_fat_percentage', 'Saturated Fat Percentage', 'Aggregated saturated fat percentage', 'percentage', true),
('AGG_SNACKS', 'snacks', 'Snacks', 'Aggregated snacks', 'count', true),
('AGG_TAKEOUTDELIVERY_MEALS', 'takeoutdelivery_meals', 'Takeout/Delivery Meals', 'Aggregated takeout/delivery meals', 'count', true),
('AGG_WATER_CONSUMPTION', 'water_consumption', 'Water Consumption', 'Aggregated water consumption', 'fluid_ounce', true),
('AGG_WHOLE_FOOD_MEALS', 'whole_food_meals', 'Whole Food Meals', 'Aggregated whole food meals', 'count', true),
('AGG_ACTIVE_TIME', 'active_time', 'Active Time', 'Aggregated active time', 'minutes', true),
('AGG_ACTIVE_TIME_SESSION', 'active_time_session', 'Active Time Session', 'Aggregated active time session', 'minutes', true),
('AGG_ACTIVE_VS_CALCULATED_TIME_DIFFERENCE', 'active_vs_calculated_time_difference', 'Active vs Calculated Time Difference', 'Aggregated active vs calculated time difference', 'minutes', true),
('AGG_CALCULATED_ACTIVE_TIME', 'calculated_active_time', 'Calculated Active Time', 'Aggregated calculated active time', 'minutes', true),
('AGG_CALCULATED_EXERCISE_TIME', 'calculated_exercise_time', 'Calculated Exercise Time', 'Aggregated calculated exercise time', 'minutes', true),
('AGG_CALORIES', 'calories', 'Calories', 'Aggregated calories', 'kilocalorie', true),
('AGG_EXERCISE_SNACK', 'exercise_snack', 'Exercise Snack', 'Aggregated exercise snack', 'count', true),
('AGG_EXERCISE_SNACKS', 'exercise_snacks', 'Exercise Snacks', 'Aggregated exercise snacks', 'count', true),
('AGG_HIIT_SESSION', 'hiit_session', 'HIIT Session', 'Aggregated hiit session', 'count', true),
('AGG_MOBILITY_SESSION', 'mobility_session', 'Mobility Session', 'Aggregated mobility session', 'count', true),
('AGG_POST_MEAL_EXERCISE_SNACKS', 'post_meal_exercise_snacks', 'Post Meal Exercise Snacks', 'Aggregated post meal exercise snacks', 'count', true),
('AGG_RESTING_HEART_RATE', 'resting_heart_rate', 'Resting Heart Rate', 'Aggregated resting heart rate', 'count', true),
('AGG_SEDENTARY_PERIOD', 'sedentary_period', 'Sedentary Period', 'Aggregated sedentary period', 'count', true),
('AGG_SEDENTARY_TIME', 'sedentary_time', 'Sedentary Time', 'Aggregated sedentary time', 'minutes', true),
('AGG_STEPS', 'steps', 'Steps', 'Aggregated steps', 'steps', true),
('AGG_STRENGTH_TRAINING_SESSION', 'strength_training_session', 'Strength Training Session', 'Aggregated strength training session', 'count', true),
('AGG_VO2_MAX', 'vo2_max', 'VO2 Max', 'Aggregated vo2 max', 'count', true),
('AGG_AWAKE_EPISODE_COUNT', 'awake_episode_count', 'Awake Episode Count', 'Aggregated awake episode count', 'count', true),
('AGG_AWAKE_PERCENTAGE', 'awake_percentage', 'Awake Percentage', 'Aggregated awake percentage', 'percentage', true),
('AGG_CORE_PERCENTAGE', 'core_percentage', 'Core Percentage', 'Aggregated core percentage', 'percentage', true),
('AGG_DEEP_PERCENTAGE', 'deep_percentage', 'Deep Percentage', 'Aggregated deep percentage', 'percentage', true),
('AGG_DEEP_SLEEP_CYCLE_COUNT', 'deep_sleep_cycle_count', 'Deep Sleep Cycle Count', 'Aggregated deep sleep cycle count', 'count', true),
('AGG_LAST_DRINK_BUFFER', 'last_drink_buffer', 'Last Drink Buffer', 'Aggregated last drink buffer', 'hours', true),
('AGG_REM_PERCENTAGE', 'rem_percentage', 'REM Percentage', 'Aggregated rem percentage', 'percentage', true),
('AGG_REM_SLEEP_CYCLE_COUNT', 'rem_sleep_cycle_count', 'REM Sleep Cycle Count', 'Aggregated rem sleep cycle count', 'count', true);

-- GRAMS Pattern (6 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_FIBER_GRAMS', 'fiber_grams', 'Fiber Grams', 'Aggregated fiber grams', 'gram', true),
('AGG_MONOUNATURATED_FAT', 'monounaturated_fat', 'Monounaturated Fat (g)', 'Aggregated monounaturated fat (g)', 'gram', true),
('AGG_PLANTBASED_PROTEIN', 'plantbased_protein', 'plant-based protein (grams)', 'Aggregated plant-based protein (grams)', 'gram', true),
('AGG_POLYUNSATURATED_FAT', 'polyunsaturated_fat', 'Polyunsaturated Fat (g)', 'Aggregated polyunsaturated fat (g)', 'gram', true),
('AGG_PROTEIN_GRAMS', 'protein_grams', 'Protein Grams', 'Aggregated protein grams', 'gram', true),
('AGG_SATURATED_FAT', 'saturated_fat', 'Saturated Fat (g)', 'Aggregated saturated fat (g)', 'gram', true);

-- RATING Pattern (5 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_FOCUS_RATING', 'focus_rating', 'Focus Rating', 'Aggregated focus rating', 'count', true),
('AGG_MEMORY_CLARITY_RATING', 'memory_clarity_rating', 'Memory Clarity Rating', 'Aggregated memory clarity rating', 'count', true),
('AGG_MOOD_RATING', 'mood_rating', 'Mood Rating', 'Aggregated mood rating', 'count', true),
('AGG_STRESS_LEVEL_RATING', 'stress_level_rating', 'Stress Level Rating', 'Aggregated stress level rating', 'count', true),
('AGG_SLEEP_ENVIRONMENT_SCORE', 'sleep_environment_score', 'Sleep Environment Score', 'Aggregated sleep environment score', 'count', true);

-- SERVINGS Pattern (13 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_ADDED_SUGAR_SERVINGS', 'added_sugar_servings', 'Added Sugar Servings', 'Aggregated added sugar servings', 'serving', true),
('AGG_BREAKFAST_TOTAL_SERVINGS', 'breakfast_total_servings', 'Breakfast Total Servings', 'Aggregated breakfast total servings', 'serving', true),
('AGG_DINNER_TOTAL_SERVINGS', 'dinner_total_servings', 'Dinner Total Servings', 'Aggregated dinner total servings', 'serving', true),
('AGG_FATTY_FISH_SERVINGS', 'fatty_fish_servings', 'Fatty Fish Servings', 'Aggregated fatty fish servings', 'serving', true),
('AGG_FIBER_SERVINGS', 'fiber_servings', 'Fiber Servings', 'Aggregated fiber servings', 'serving', true),
('AGG_FRUIT_SERVINGS', 'fruit_servings', 'Fruit Servings', 'Aggregated fruit servings', 'serving', true),
('AGG_LEGUME_SERVINGS', 'legume_servings', 'Legume Servings', 'Aggregated legume servings', 'serving', true),
('AGG_LUNCH_TOTAL_SERVINGS', 'lunch_total_servings', 'Lunch Total Servings', 'Aggregated lunch total servings', 'serving', true),
('AGG_PROTEIN_SERVINGS', 'protein_servings', 'Protein Servings', 'Aggregated protein servings', 'serving', true),
('AGG_RED_MEAT_SERVINGS', 'red_meat_servings', 'Red Meat Servings', 'Aggregated red meat servings', 'serving', true),
('AGG_SEED_SERVINGS', 'seed_servings', 'Seed Servings', 'Aggregated seed servings', 'serving', true),
('AGG_ULTRAPROCESSED_FOOD_SERVINGS', 'ultraprocessed_food_servings', 'Ultraprocessed Food Servings', 'Aggregated ultraprocessed food servings', 'serving', true),
('AGG_WHOLE_GRAIN_SERVINGS', 'whole_grain_servings', 'Whole Grain Servings', 'Aggregated whole grain servings', 'serving', true);

-- SESSION_COUNT Pattern (24 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_BRAIN_TRAINING_SESSIONS', 'brain_training_sessions', 'Brain Training Sessions', 'Aggregated brain training sessions', 'count', true),
('AGG_JOURNALING_SESSIONS', 'journaling_sessions', 'Journaling Sessions', 'Aggregated journaling sessions', 'count', true),
('AGG_SUNLIGHT_EXPOSURE_SESSIONS', 'sunlight_exposure_sessions', 'Sunlight Exposure Sessions', 'Aggregated sunlight exposure sessions', 'count', true),
('AGG_GRATITUDE_SESSIONS', 'gratitude_sessions', 'Gratitude Sessions', 'Aggregated gratitude sessions', 'count', true),
('AGG_MINDFULNESS_SESSIONS', 'mindfulness_sessions', 'Mindfulness Sessions', 'Aggregated mindfulness sessions', 'count', true),
('AGG_OUTDOOR_TIME_SESSIONS', 'outdoor_time_sessions', 'Outdoor Time Sessions', 'Aggregated outdoor time sessions', 'minutes', true),
('AGG_SCREEN_TIME_SESSIONS', 'screen_time_sessions', 'Screen Time Sessions', 'Aggregated screen time sessions', 'minutes', true),
('AGG_BRUSHING_SESSIONS', 'brushing_sessions', 'Brushing Sessions', 'Aggregated brushing sessions', 'count', true),
('AGG_FLOSSING_SESSIONS', 'flossing_sessions', 'Flossing Sessions', 'Aggregated flossing sessions', 'count', true),
('AGG_ACTIVITY_SESSIONS', 'activity_sessions', 'Activity Sessions', 'Aggregated activity sessions', 'count', true),
('AGG_CARDIO_SESSIONS', 'cardio_sessions', 'Cardio Sessions', 'Aggregated cardio sessions', 'count', true),
('AGG_HIIT_SESSIONS', 'hiit_sessions', 'HIIT Sessions', 'Aggregated hiit sessions', 'count', true),
('AGG_MOBILITY_SESSIONS', 'mobility_sessions', 'Mobility Sessions', 'Aggregated mobility sessions', 'count', true),
('AGG_POST_MEAL_ACTIVITY_SESSIONS', 'post_meal_activity_sessions', 'Post Meal Activity Sessions', 'Aggregated post meal activity sessions', 'count', true),
('AGG_SEDENTARY_SESSIONS', 'sedentary_sessions', 'Sedentary Sessions', 'Aggregated sedentary sessions', 'count', true),
('AGG_STRENGTH_SESSIONS', 'strength_sessions', 'Strength Sessions', 'Aggregated strength sessions', 'count', true),
('AGG_STRENGTH_TRAINING_SESSIONS', 'strength_training_sessions', 'Strength Training Sessions', 'Aggregated strength training sessions', 'count', true),
('AGG_WALKING_SESSIONS', 'walking_sessions', 'Walking Sessions', 'Aggregated walking sessions', 'count', true),
('AGG_ZONE_2_CARDIO_SESSIONS', 'zone_2_cardio_sessions', 'Zone 2 Cardio Sessions', 'Aggregated zone 2 cardio sessions', 'count', true),
('AGG_SLEEP_SESSIONS', 'sleep_sessions', 'Sleep Sessions', 'Aggregated sleep sessions', 'count', true),
('AGG_BREATHWORK_AND_MINDFULNESS_SESSIONS', 'breathwork_and_mindfulness_sessions', 'Breathwork AND Mindfulness Sessions', 'Aggregated breathwork and mindfulness sessions', 'count', true),
('AGG_BREATHWORK_SESSIONS', 'breathwork_sessions', 'Breathwork Sessions', 'Aggregated breathwork sessions', 'count', true),
('AGG_MEDITATION_SESSIONS', 'meditation_sessions', 'Meditation Sessions', 'Aggregated meditation sessions', 'count', true),
('AGG_STRESS_MANAGEMENT_SESSIONS', 'stress_management_sessions', 'Stress Management Sessions', 'Aggregated stress management sessions', 'count', true);

-- VARIETY Pattern (7 metrics)
INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_FAT_SOURCE_COUNT', 'fat_source_count', 'Fat Source Count', 'Aggregated fat source count', 'count', true),
('AGG_FIBER_SOURCE_COUNT', 'fiber_source_count', 'Fiber Source Count', 'Aggregated fiber source count', 'count', true),
('AGG_FRUIT_SOURCE_COUNT', 'fruit_source_count', 'Fruit Source Count', 'Aggregated fruit source count', 'count', true),
('AGG_LEGUME_SOURCE_COUNT', 'legume_source_count', 'Legume Source Count', 'Aggregated legume source count', 'count', true),
('AGG_VEGETABLE_SOURCE_COUNT', 'vegetable_source_count', 'Vegetable Source Count', 'Aggregated vegetable source count', 'count', true),
('AGG_WHOLE_GRAIN_SOURCE_COUNT', 'whole_grain_source_count', 'Whole Grain Source Count', 'Aggregated whole grain source count', 'count', true),
('AGG_CAFFEINE_SOURCE_COUNT', 'caffeine_source_count', 'Caffeine Source Count', 'Aggregated caffeine source count', 'count', true);


-- =====================================================
-- PART 2: Create Aggregation Metrics Periods Config
-- =====================================================

-- BASELINE_COMPARISON Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_ALCOHOLIC_DRINKS_VS_BASELINE', 'daily', 'comparison_view', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_ALCOHOLIC_DRINKS_VS_BASELINE', 'weekly', 'comparison_view', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_ALCOHOLIC_DRINKS_VS_BASELINE', 'monthly', 'comparison_view', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_CIGARETTES_VS_BASELINE', 'daily', 'comparison_view', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_CIGARETTES_VS_BASELINE', 'weekly', 'comparison_view', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_CIGARETTES_VS_BASELINE', 'monthly', 'comparison_view', 'date', 'day', 33, 33, 0, 100, 'count', true);

-- COMPLIANCE Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_EVENING_ROUTINE_ADHERENCE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_EVENING_ROUTINE_ADHERENCE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_EVENING_ROUTINE_ADHERENCE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_MEDICATION_ADHERENCE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_MEDICATION_ADHERENCE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_MEDICATION_ADHERENCE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_PEPTIDE_ADHERENCE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_PEPTIDE_ADHERENCE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_PEPTIDE_ADHERENCE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_SKINCARE_ROUTINE_ADHERENCE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_SKINCARE_ROUTINE_ADHERENCE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_SKINCARE_ROUTINE_ADHERENCE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_SUPPLEMENT_ADHERENCE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_SUPPLEMENT_ADHERENCE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_SUPPLEMENT_ADHERENCE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_SLEEP_ROUTINE_ADHERENCE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_SLEEP_ROUTINE_ADHERENCE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_SLEEP_ROUTINE_ADHERENCE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true);

-- CONSISTENCY Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_SLEEP_TIME_CONSISTENCY', 'daily', 'gauge', 'date', 'hour', 24, 1, 0, 100, 'hours', true),
('AGG_SLEEP_TIME_CONSISTENCY', 'weekly', 'gauge', 'date', 'day', 7, 7, 0, 100, 'hours', true),
('AGG_SLEEP_TIME_CONSISTENCY', 'monthly', 'gauge', 'date', 'day', 33, 33, 0, 100, 'hours', true),
('AGG_WAKE_TIME_CONSISTENCY', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_WAKE_TIME_CONSISTENCY', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_WAKE_TIME_CONSISTENCY', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true);

-- CURRENT_VALUE Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_SOCIAL_INTERACTION', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SOCIAL_INTERACTION', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SOCIAL_INTERACTION', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_BMI', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_BMI', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_BMI', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_BREAST_MRI_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_BREAST_MRI_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_BREAST_MRI_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_CERVICAL_SCREENING_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_CERVICAL_SCREENING_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_CERVICAL_SCREENING_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_CIGARETTES', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_CIGARETTES', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_CIGARETTES', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_COLONOSCOPY_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_COLONOSCOPY_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_COLONOSCOPY_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_DENTAL_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_DENTAL_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_DENTAL_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_DIGITAL_SHUTOFF_BUFFER', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'hours', true),
('AGG_DIGITAL_SHUTOFF_BUFFER', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'hours', true),
('AGG_DIGITAL_SHUTOFF_BUFFER', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'hours', true),
('AGG_MAMMOGRAM_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_MAMMOGRAM_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_MAMMOGRAM_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_MONTHS_SINCE_LAST_BREAST_MRI', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_BREAST_MRI', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_BREAST_MRI', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_DENTAL_EXAM', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_DENTAL_EXAM', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_DENTAL_EXAM', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_MAMMOGRAM', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_MAMMOGRAM', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_MAMMOGRAM', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_SKIN_CHECK', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_SKIN_CHECK', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_SKIN_CHECK', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_VISION_CHECK', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_VISION_CHECK', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_MONTHS_SINCE_LAST_VISION_CHECK', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_MORNING_SUNSCREEN_APPLICATIONS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_MORNING_SUNSCREEN_APPLICATIONS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_MORNING_SUNSCREEN_APPLICATIONS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_PHYSICAL_EXAM_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_PHYSICAL_EXAM_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_PHYSICAL_EXAM_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_PSA_TEST_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_PSA_TEST_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_PSA_TEST_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_SKIN_CHECK_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_SKIN_CHECK_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_SKIN_CHECK_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_SUNSCREEN_APPLICATIONS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SUNSCREEN_APPLICATIONS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SUNSCREEN_APPLICATIONS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SUNSCREEN_COMPLIANCE_EVENTS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_SUNSCREEN_COMPLIANCE_EVENTS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_SUNSCREEN_COMPLIANCE_EVENTS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_SUNSCREEN_COMPLIANCE_RATE', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_SUNSCREEN_COMPLIANCE_RATE', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_SUNSCREEN_COMPLIANCE_RATE', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_USER_AGE', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_USER_AGE', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_USER_AGE', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_VISION_CHECK_COMPLIANCE_STATUS', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_VISION_CHECK_COMPLIANCE_STATUS', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_VISION_CHECK_COMPLIANCE_STATUS', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_YEARS_SINCE_LAST_COLONOSCOPY', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_COLONOSCOPY', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_COLONOSCOPY', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_HPV_SCREENING', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_HPV_SCREENING', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_HPV_SCREENING', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PAP_TEST', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PAP_TEST', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PAP_TEST', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PHYSICAL', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PHYSICAL', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PHYSICAL', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PSA_TEST', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PSA_TEST', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'months', true),
('AGG_YEARS_SINCE_LAST_PSA_TEST', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'months', true),
('AGG_BREAKFAST', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_BREAKFAST', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_BREAKFAST', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_DINNER', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_DINNER', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_DINNER', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_FAT_SOURCES', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_FAT_SOURCES', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_FAT_SOURCES', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_FIBER_SOURCES', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_FIBER_SOURCES', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_FIBER_SOURCES', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_FIRST_MEAL_DELAY', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_FIRST_MEAL_DELAY', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_FIRST_MEAL_DELAY', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_FRUIT_SOURCES', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_FRUIT_SOURCES', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_FRUIT_SOURCES', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_HEALTHY_FAT_USAGE', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_HEALTHY_FAT_USAGE', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_HEALTHY_FAT_USAGE', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_LAST_LARGE_MEAL_BUFFER', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'hours', true),
('AGG_LAST_LARGE_MEAL_BUFFER', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'hours', true),
('AGG_LAST_LARGE_MEAL_BUFFER', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'hours', true),
('AGG_LAST_LARGE_MEAL_TIME', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_LAST_LARGE_MEAL_TIME', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_LAST_LARGE_MEAL_TIME', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_LAST_MEAL_BUFFER', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'hours', true),
('AGG_LAST_MEAL_BUFFER', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'hours', true),
('AGG_LAST_MEAL_BUFFER', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'hours', true),
('AGG_LEGUME_SOURCES', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_LEGUME_SOURCES', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_LEGUME_SOURCES', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_LUNCH', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_LUNCH', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_LUNCH', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_MINDFUL_EATING', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_MINDFUL_EATING', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_MINDFUL_EATING', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_PLANT_BASED_MEAL', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_PLANT_BASED_MEAL', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_PLANT_BASED_MEAL', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_UNHEALTHY_FAT_USAGE', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_UNHEALTHY_FAT_USAGE', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_UNHEALTHY_FAT_USAGE', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_VEGETABLE_SOURCES', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_VEGETABLE_SOURCES', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_VEGETABLE_SOURCES', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_WHOLE_GRAIN_SOURCES', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_WHOLE_GRAIN_SOURCES', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_WHOLE_GRAIN_SOURCES', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_CAFFEINE_SOURCES', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_CAFFEINE_SOURCES', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_CAFFEINE_SOURCES', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_ZONE_2_CARDIO_SESSION', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_ZONE_2_CARDIO_SESSION', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_ZONE_2_CARDIO_SESSION', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_LAST_ALCOHOLIC_DRINK_TIME', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_LAST_ALCOHOLIC_DRINK_TIME', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_LAST_ALCOHOLIC_DRINK_TIME', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_LAST_DIGITAL_DEVICE_TIME_USAGE', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_LAST_DIGITAL_DEVICE_TIME_USAGE', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_LAST_DIGITAL_DEVICE_TIME_USAGE', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_SLEEP_EFFICIENCY', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SLEEP_EFFICIENCY', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SLEEP_EFFICIENCY', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SLEEP_LATENCY', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'hours', true),
('AGG_SLEEP_LATENCY', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'hours', true),
('AGG_SLEEP_LATENCY', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'hours', true),
('AGG_TOTAL_SLEEP_WINDOW', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_TOTAL_SLEEP_WINDOW', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_TOTAL_SLEEP_WINDOW', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_WEARABLE_USAGE', 'daily', 'current_value', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_WEARABLE_USAGE', 'weekly', 'current_value', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_WEARABLE_USAGE', 'monthly', 'current_value', 'date', 'day', 33, 33, 0, 100, 'count', true);

-- DURATION Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_BRAIN_TRAINING_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_BRAIN_TRAINING_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_BRAIN_TRAINING_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_EARLY_MORNING_LIGHT_EXPOSURE_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_EARLY_MORNING_LIGHT_EXPOSURE_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_EARLY_MORNING_LIGHT_EXPOSURE_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_SUNLIGHT_EXPOSURE_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_SUNLIGHT_EXPOSURE_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_SUNLIGHT_EXPOSURE_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_MINDFULNESS_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_MINDFULNESS_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_MINDFULNESS_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_MORNING_OUTDOOR_TIME_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_MORNING_OUTDOOR_TIME_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_MORNING_OUTDOOR_TIME_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_OUTDOOR_TIME_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_OUTDOOR_TIME_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_OUTDOOR_TIME_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_SCREEN_TIME_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_SCREEN_TIME_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_SCREEN_TIME_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_STRESS_MANAGEMENT_DURATION', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_STRESS_MANAGEMENT_DURATION', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_STRESS_MANAGEMENT_DURATION', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_WALKING_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_WALKING_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_WALKING_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_EATING_WINDOW_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_EATING_WINDOW_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_EATING_WINDOW_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_HIIT_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_HIIT_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_HIIT_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_MOBILITY_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_MOBILITY_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_MOBILITY_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_POST_MEAL_ACTIVITY_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_POST_MEAL_ACTIVITY_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_POST_MEAL_ACTIVITY_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_STRENGTH_TRAINING_DURATION', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_STRENGTH_TRAINING_DURATION', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_STRENGTH_TRAINING_DURATION', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_ZONE_2_CARDIO_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_ZONE_2_CARDIO_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_ZONE_2_CARDIO_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_AWAKE_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_AWAKE_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_AWAKE_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_AWAKE_PERIOD_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_AWAKE_PERIOD_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_AWAKE_PERIOD_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_CORE_SLEEP_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_CORE_SLEEP_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_CORE_SLEEP_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_CORE_SLEEP_PERIOD_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_CORE_SLEEP_PERIOD_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_CORE_SLEEP_PERIOD_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_DEEP_SLEEP_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_DEEP_SLEEP_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_DEEP_SLEEP_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_DEEP_SLEEP_PERIOD_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_DEEP_SLEEP_PERIOD_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_DEEP_SLEEP_PERIOD_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_PERIOD_AWAKE_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_PERIOD_AWAKE_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_PERIOD_AWAKE_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_PERIOD_CORE_SLEEP_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_PERIOD_CORE_SLEEP_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_PERIOD_CORE_SLEEP_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_PERIOD_DEEP_SLEEP_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_PERIOD_DEEP_SLEEP_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_PERIOD_DEEP_SLEEP_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_PERIOD_REM_SLEEP_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_PERIOD_REM_SLEEP_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_PERIOD_REM_SLEEP_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_REM_SLEEP_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_REM_SLEEP_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_REM_SLEEP_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_REM_SLEEP_PERIOD_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_REM_SLEEP_PERIOD_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_REM_SLEEP_PERIOD_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_TIME_IN_BED_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_TIME_IN_BED_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_TIME_IN_BED_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_TOTAL_SLEEP_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'hours', true),
('AGG_TOTAL_SLEEP_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'hours', true),
('AGG_TOTAL_SLEEP_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'hours', true),
('AGG_BREATHWORK_AND_MINDFULNESS_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_BREATHWORK_AND_MINDFULNESS_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_BREATHWORK_AND_MINDFULNESS_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_BREATHWORK_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_BREATHWORK_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_BREATHWORK_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true),
('AGG_MEDITATION_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minutes', true),
('AGG_MEDITATION_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minutes', true),
('AGG_MEDITATION_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minutes', true);

-- GENERAL Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_ALCOHOLIC_DRINKS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_ALCOHOLIC_DRINKS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_ALCOHOLIC_DRINKS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_BODY_FAT_PERCENTAGE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_BODY_FAT_PERCENTAGE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_BODY_FAT_PERCENTAGE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_CURRENT_WEIGHT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_CURRENT_WEIGHT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_CURRENT_WEIGHT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_DIASTOLIC_BLOOD_PRESSURE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_DIASTOLIC_BLOOD_PRESSURE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_DIASTOLIC_BLOOD_PRESSURE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_HEIGHT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_HEIGHT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_HEIGHT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_HIP_TO_WAIST_RATIO', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'ratio', true),
('AGG_HIP_TO_WAIST_RATIO', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'ratio', true),
('AGG_HIP_TO_WAIST_RATIO', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'ratio', true),
('AGG_LAST_CAFFEINE_CONSUMPTION_BUFFER', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'hours', true),
('AGG_LAST_CAFFEINE_CONSUMPTION_BUFFER', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'hours', true),
('AGG_LAST_CAFFEINE_CONSUMPTION_BUFFER', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'hours', true),
('AGG_LAST_CAFFEINE_CONSUMPTION_TIME', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_LAST_CAFFEINE_CONSUMPTION_TIME', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_LAST_CAFFEINE_CONSUMPTION_TIME', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_SYSTOLIC_BLOOD_PRESSURE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SYSTOLIC_BLOOD_PRESSURE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SYSTOLIC_BLOOD_PRESSURE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_ADDED_SUGAR_CONSUMED', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_ADDED_SUGAR_CONSUMED', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_ADDED_SUGAR_CONSUMED', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_CAFFEINE_CONSUMED', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_CAFFEINE_CONSUMED', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_CAFFEINE_CONSUMED', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_FIRST_MEAL_TIME', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_FIRST_MEAL_TIME', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_FIRST_MEAL_TIME', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_HEALTHY_FAT_RATIO', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'ratio', true),
('AGG_HEALTHY_FAT_RATIO', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'ratio', true),
('AGG_HEALTHY_FAT_RATIO', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'ratio', true),
('AGG_HEALTHY_FAT_SWAPS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_HEALTHY_FAT_SWAPS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_HEALTHY_FAT_SWAPS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_LARGE_MEALS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_LARGE_MEALS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_LARGE_MEALS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_LAST_MEAL_TIME', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_LAST_MEAL_TIME', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_LAST_MEAL_TIME', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_MEALS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_MEALS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_MEALS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_MINDFUL_EATING_EPISODES', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_MINDFUL_EATING_EPISODES', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_MINDFUL_EATING_EPISODES', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_PLANT_BASED_MEALS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_PLANT_BASED_MEALS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_PLANT_BASED_MEALS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_PLANTBASED_PROTEIN_PERCENTAGE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_PLANTBASED_PROTEIN_PERCENTAGE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_PLANTBASED_PROTEIN_PERCENTAGE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_PROCESS_MEAT', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_PROCESS_MEAT', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_PROCESS_MEAT', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_PROCESSED_MEAT_SERVING', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_PROCESSED_MEAT_SERVING', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_PROCESSED_MEAT_SERVING', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_PROTEIN_PER_KILOGRAM_BODY_WEIGHT', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_PROTEIN_PER_KILOGRAM_BODY_WEIGHT', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_PROTEIN_PER_KILOGRAM_BODY_WEIGHT', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SATURATED_FAT_PERCENTAGE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_SATURATED_FAT_PERCENTAGE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_SATURATED_FAT_PERCENTAGE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_SNACKS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SNACKS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SNACKS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_TAKEOUTDELIVERY_MEALS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_TAKEOUTDELIVERY_MEALS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_TAKEOUTDELIVERY_MEALS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_WATER_CONSUMPTION', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 100, 'fluid_ounce', true),
('AGG_WATER_CONSUMPTION', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 100, 'fluid_ounce', true),
('AGG_WATER_CONSUMPTION', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 100, 'fluid_ounce', true),
('AGG_WHOLE_FOOD_MEALS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_WHOLE_FOOD_MEALS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_WHOLE_FOOD_MEALS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_ACTIVE_TIME', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_ACTIVE_TIME', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_ACTIVE_TIME', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_ACTIVE_TIME_SESSION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_ACTIVE_TIME_SESSION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_ACTIVE_TIME_SESSION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_ACTIVE_VS_CALCULATED_TIME_DIFFERENCE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_ACTIVE_VS_CALCULATED_TIME_DIFFERENCE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_ACTIVE_VS_CALCULATED_TIME_DIFFERENCE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_CALCULATED_ACTIVE_TIME', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_CALCULATED_ACTIVE_TIME', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_CALCULATED_ACTIVE_TIME', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_CALCULATED_EXERCISE_TIME', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_CALCULATED_EXERCISE_TIME', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_CALCULATED_EXERCISE_TIME', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_CALORIES', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'kilocalorie', true),
('AGG_CALORIES', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'kilocalorie', true),
('AGG_CALORIES', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'kilocalorie', true),
('AGG_EXERCISE_SNACK', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_EXERCISE_SNACK', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_EXERCISE_SNACK', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_EXERCISE_SNACKS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_EXERCISE_SNACKS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_EXERCISE_SNACKS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_HIIT_SESSION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_HIIT_SESSION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_HIIT_SESSION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_MOBILITY_SESSION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_MOBILITY_SESSION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_MOBILITY_SESSION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_POST_MEAL_EXERCISE_SNACKS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_POST_MEAL_EXERCISE_SNACKS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_POST_MEAL_EXERCISE_SNACKS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_RESTING_HEART_RATE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_RESTING_HEART_RATE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_RESTING_HEART_RATE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SEDENTARY_PERIOD', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SEDENTARY_PERIOD', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SEDENTARY_PERIOD', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SEDENTARY_TIME', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'minutes', true),
('AGG_SEDENTARY_TIME', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'minutes', true),
('AGG_SEDENTARY_TIME', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'minutes', true),
('AGG_STEPS', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 100, 'steps', true),
('AGG_STEPS', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 100, 'steps', true),
('AGG_STEPS', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 100, 'steps', true),
('AGG_STRENGTH_TRAINING_SESSION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_STRENGTH_TRAINING_SESSION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_STRENGTH_TRAINING_SESSION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_VO2_MAX', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_VO2_MAX', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_VO2_MAX', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_AWAKE_EPISODE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_AWAKE_EPISODE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_AWAKE_EPISODE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_AWAKE_PERCENTAGE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_AWAKE_PERCENTAGE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_AWAKE_PERCENTAGE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_CORE_PERCENTAGE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_CORE_PERCENTAGE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_CORE_PERCENTAGE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_DEEP_PERCENTAGE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_DEEP_PERCENTAGE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_DEEP_PERCENTAGE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_DEEP_SLEEP_CYCLE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_DEEP_SLEEP_CYCLE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_DEEP_SLEEP_CYCLE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_LAST_DRINK_BUFFER', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'hours', true),
('AGG_LAST_DRINK_BUFFER', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'hours', true),
('AGG_LAST_DRINK_BUFFER', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'hours', true),
('AGG_REM_PERCENTAGE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 100, 'percentage', true),
('AGG_REM_PERCENTAGE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 100, 'percentage', true),
('AGG_REM_PERCENTAGE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 100, 'percentage', true),
('AGG_REM_SLEEP_CYCLE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_REM_SLEEP_CYCLE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_REM_SLEEP_CYCLE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true);

-- GRAMS Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_FIBER_GRAMS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 150, 'gram', true),
('AGG_FIBER_GRAMS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 150, 'gram', true),
('AGG_FIBER_GRAMS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 150, 'gram', true),
('AGG_MONOUNATURATED_FAT', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 150, 'gram', true),
('AGG_MONOUNATURATED_FAT', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 150, 'gram', true),
('AGG_MONOUNATURATED_FAT', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 150, 'gram', true),
('AGG_PLANTBASED_PROTEIN', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 150, 'gram', true),
('AGG_PLANTBASED_PROTEIN', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 150, 'gram', true),
('AGG_PLANTBASED_PROTEIN', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 150, 'gram', true),
('AGG_POLYUNSATURATED_FAT', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 150, 'gram', true),
('AGG_POLYUNSATURATED_FAT', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 150, 'gram', true),
('AGG_POLYUNSATURATED_FAT', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 150, 'gram', true),
('AGG_PROTEIN_GRAMS', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 150, 'gram', true),
('AGG_PROTEIN_GRAMS', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 150, 'gram', true),
('AGG_PROTEIN_GRAMS', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 150, 'gram', true),
('AGG_SATURATED_FAT', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 150, 'gram', true),
('AGG_SATURATED_FAT', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 150, 'gram', true),
('AGG_SATURATED_FAT', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 150, 'gram', true);

-- RATING Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_FOCUS_RATING', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_FOCUS_RATING', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_FOCUS_RATING', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_MEMORY_CLARITY_RATING', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_MEMORY_CLARITY_RATING', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_MEMORY_CLARITY_RATING', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_MOOD_RATING', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_MOOD_RATING', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_MOOD_RATING', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_STRESS_LEVEL_RATING', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_STRESS_LEVEL_RATING', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_STRESS_LEVEL_RATING', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_SLEEP_ENVIRONMENT_SCORE', 'daily', 'trend_line', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_SLEEP_ENVIRONMENT_SCORE', 'weekly', 'trend_line', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_SLEEP_ENVIRONMENT_SCORE', 'monthly', 'trend_line', 'date', 'day', 33, 33, 0, 10, 'count', true);

-- SERVINGS Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_ADDED_SUGAR_SERVINGS', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_ADDED_SUGAR_SERVINGS', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_ADDED_SUGAR_SERVINGS', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_BREAKFAST_TOTAL_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_BREAKFAST_TOTAL_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_BREAKFAST_TOTAL_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_DINNER_TOTAL_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_DINNER_TOTAL_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_DINNER_TOTAL_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_FATTY_FISH_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_FATTY_FISH_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_FATTY_FISH_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_FIBER_SERVINGS', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_FIBER_SERVINGS', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_FIBER_SERVINGS', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_FRUIT_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_FRUIT_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_FRUIT_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_LEGUME_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_LEGUME_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_LEGUME_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_LUNCH_TOTAL_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_LUNCH_TOTAL_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_LUNCH_TOTAL_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_PROTEIN_SERVINGS', 'daily', 'progress_bar', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_PROTEIN_SERVINGS', 'weekly', 'progress_bar', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_PROTEIN_SERVINGS', 'monthly', 'progress_bar', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_RED_MEAT_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_RED_MEAT_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_RED_MEAT_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_SEED_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_SEED_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_SEED_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_ULTRAPROCESSED_FOOD_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_ULTRAPROCESSED_FOOD_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_ULTRAPROCESSED_FOOD_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true),
('AGG_WHOLE_GRAIN_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'serving', true),
('AGG_WHOLE_GRAIN_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'serving', true),
('AGG_WHOLE_GRAIN_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'serving', true);

-- SESSION_COUNT Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_BRAIN_TRAINING_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_BRAIN_TRAINING_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_BRAIN_TRAINING_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_JOURNALING_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_JOURNALING_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_JOURNALING_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_SUNLIGHT_EXPOSURE_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_SUNLIGHT_EXPOSURE_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_SUNLIGHT_EXPOSURE_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_GRATITUDE_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_GRATITUDE_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_GRATITUDE_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_MINDFULNESS_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_MINDFULNESS_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_MINDFULNESS_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_OUTDOOR_TIME_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'minutes', true),
('AGG_OUTDOOR_TIME_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'minutes', true),
('AGG_OUTDOOR_TIME_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'minutes', true),
('AGG_SCREEN_TIME_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'minutes', true),
('AGG_SCREEN_TIME_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'minutes', true),
('AGG_SCREEN_TIME_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'minutes', true),
('AGG_BRUSHING_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_BRUSHING_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_BRUSHING_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_FLOSSING_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_FLOSSING_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_FLOSSING_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_ACTIVITY_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_ACTIVITY_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_ACTIVITY_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_CARDIO_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_CARDIO_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_CARDIO_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_HIIT_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_HIIT_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_HIIT_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_MOBILITY_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_MOBILITY_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_MOBILITY_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_POST_MEAL_ACTIVITY_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_POST_MEAL_ACTIVITY_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_POST_MEAL_ACTIVITY_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_SEDENTARY_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_SEDENTARY_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_SEDENTARY_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_STRENGTH_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_STRENGTH_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_STRENGTH_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_STRENGTH_TRAINING_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_STRENGTH_TRAINING_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_STRENGTH_TRAINING_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_WALKING_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_WALKING_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_WALKING_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_ZONE_2_CARDIO_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_ZONE_2_CARDIO_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_ZONE_2_CARDIO_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_SLEEP_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_SLEEP_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_SLEEP_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_BREATHWORK_AND_MINDFULNESS_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_BREATHWORK_AND_MINDFULNESS_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_BREATHWORK_AND_MINDFULNESS_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_BREATHWORK_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_BREATHWORK_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_BREATHWORK_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_MEDITATION_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_MEDITATION_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_MEDITATION_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true),
('AGG_STRESS_MANAGEMENT_SESSIONS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 5, 'count', true),
('AGG_STRESS_MANAGEMENT_SESSIONS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 5, 'count', true),
('AGG_STRESS_MANAGEMENT_SESSIONS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 5, 'count', true);

-- VARIETY Pattern
INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_FAT_SOURCE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 15, 'count', true),
('AGG_FAT_SOURCE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 15, 'count', true),
('AGG_FAT_SOURCE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 15, 'count', true),
('AGG_FIBER_SOURCE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 15, 'count', true),
('AGG_FIBER_SOURCE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 15, 'count', true),
('AGG_FIBER_SOURCE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 15, 'count', true),
('AGG_FRUIT_SOURCE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 15, 'count', true),
('AGG_FRUIT_SOURCE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 15, 'count', true),
('AGG_FRUIT_SOURCE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 15, 'count', true),
('AGG_LEGUME_SOURCE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 15, 'count', true),
('AGG_LEGUME_SOURCE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 15, 'count', true),
('AGG_LEGUME_SOURCE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 15, 'count', true),
('AGG_VEGETABLE_SOURCE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 15, 'count', true),
('AGG_VEGETABLE_SOURCE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 15, 'count', true),
('AGG_VEGETABLE_SOURCE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 15, 'count', true),
('AGG_WHOLE_GRAIN_SOURCE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 15, 'count', true),
('AGG_WHOLE_GRAIN_SOURCE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 15, 'count', true),
('AGG_WHOLE_GRAIN_SOURCE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 15, 'count', true),
('AGG_CAFFEINE_SOURCE_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 15, 'count', true),
('AGG_CAFFEINE_SOURCE_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 15, 'count', true),
('AGG_CAFFEINE_SOURCE_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 15, 'count', true);


-- =====================================================
-- Summary
-- =====================================================

DO $$
DECLARE
  agg_count INT;
  period_count INT;
BEGIN
  SELECT COUNT(*) INTO agg_count FROM aggregation_metrics;
  SELECT COUNT(*) INTO period_count FROM aggregation_metrics_periods;

  RAISE NOTICE '✅ Aggregation Metrics Created';
  RAISE NOTICE '';
  RAISE NOTICE 'Total aggregation_metrics: %', agg_count;
  RAISE NOTICE 'Total aggregation_metrics_periods: %', period_count;
  RAISE NOTICE '';
  RAISE NOTICE 'Ready to create display_metrics!';
END $$;

COMMIT;
