-- =====================================================
-- Create Aggregation Metrics Dependencies
-- =====================================================
-- Links aggregation_metrics to their source calculations/fields
--
-- Created: 2025-10-22
-- =====================================================

BEGIN;

-- =====================================================
-- PART 1: Create Dependencies for Existing Metrics
-- =====================================================

INSERT INTO aggregation_metrics_dependencies
(agg_metric_id, dependency_type, instance_calculation_id, data_entry_field_id)
VALUES
('AGG_BMI', 'instance_calc', 'CALC_BMI', NULL),
('AGG_BMR', 'instance_calc', 'CALC_BMR', NULL),
('AGG_BODY_FAT_PERCENTAGE', 'instance_calc', 'CALC_BODY_FAT_PERCENTAGE', NULL),
('AGG_BRAIN_TRAINING_DURATION', 'instance_calc', 'CALC_BRAIN_TRAINING_DURATION', NULL),
('AGG_BRAIN_TRAINING_SESSION_COUNT', 'instance_calc', 'CALC_BRAIN_TRAINING_SESSION_COUNT', NULL),
('AGG_CARDIO_DURATION', 'instance_calc', 'CALC_CARDIO_DURATION', NULL),
('AGG_CARDIO_SESSION_COUNT', 'instance_calc', 'CALC_CARDIO_SESSION_COUNT', NULL),
('AGG_DISTANCE_KM_TO_MILES', 'instance_calc', 'CALC_DISTANCE_KM_TO_MILES', NULL),
('AGG_DISTANCE_MILES_TO_KM', 'instance_calc', 'CALC_DISTANCE_MILES_TO_KM', NULL),
('AGG_FAT_GRAMS_TO_SERVINGS', 'instance_calc', 'CALC_FAT_GRAMS_TO_SERVINGS', NULL),
('AGG_FAT_SERVINGS_TO_GRAMS', 'instance_calc', 'CALC_FAT_SERVINGS_TO_GRAMS', NULL),
('AGG_FIBER_GRAMS_TO_SERVINGS', 'instance_calc', 'CALC_FIBER_GRAMS_TO_SERVINGS', NULL),
('AGG_FIBER_SERVINGS_TO_GRAMS', 'instance_calc', 'CALC_FIBER_SERVINGS_TO_GRAMS', NULL),
('AGG_FLEXIBILITY_SESSION_COUNT', 'instance_calc', 'CALC_FLEXIBILITY_SESSION_COUNT', NULL),
('AGG_FRUIT_TYPE_TO_NUTRITION', 'instance_calc', 'CALC_FRUIT_TYPE_TO_NUTRITION', NULL),
('AGG_HIIT_DURATION', 'instance_calc', 'CALC_HIIT_DURATION', NULL),
('AGG_HIIT_SESSION_COUNT', 'instance_calc', 'CALC_HIIT_SESSION_COUNT', NULL),
('AGG_HIP_IN_TO_CM', 'instance_calc', 'CALC_HIP_IN_TO_CM', NULL),
('AGG_HIP_WAIST_RATIO', 'instance_calc', 'CALC_HIP_WAIST_RATIO', NULL),
('AGG_JOURNALING_DURATION', 'instance_calc', 'CALC_JOURNALING_DURATION', NULL),
('AGG_JOURNALING_SESSION_COUNT', 'instance_calc', 'CALC_JOURNALING_SESSION_COUNT', NULL),
('AGG_LEAN_BODY_MASS', 'instance_calc', 'CALC_LEAN_BODY_MASS', NULL),
('AGG_LEGUME_TYPE_TO_NUTRITION', 'instance_calc', 'CALC_LEGUME_TYPE_TO_NUTRITION', NULL),
('AGG_MINDFULNESS_DURATION', 'instance_calc', 'CALC_MINDFULNESS_DURATION', NULL),
('AGG_MINDFULNESS_SESSION_COUNT', 'instance_calc', 'CALC_MINDFULNESS_SESSION_COUNT', NULL),
('AGG_MOBILITY_DURATION', 'instance_calc', 'CALC_MOBILITY_DURATION', NULL),
('AGG_MOBILITY_SESSION_COUNT', 'instance_calc', 'CALC_MOBILITY_SESSION_COUNT', NULL),
('AGG_NECK_IN_TO_CM', 'instance_calc', 'CALC_NECK_IN_TO_CM', NULL),
('AGG_NUT_SEED_TYPE_TO_NUTRITION', 'instance_calc', 'CALC_NUT_SEED_TYPE_TO_NUTRITION', NULL),
('AGG_OUTDOOR_DURATION', 'instance_calc', 'CALC_OUTDOOR_DURATION', NULL),
('AGG_OUTDOOR_SESSION_COUNT', 'instance_calc', 'CALC_OUTDOOR_SESSION_COUNT', NULL),
('AGG_PROTEIN_GRAMS_TO_SERVINGS', 'instance_calc', 'CALC_PROTEIN_GRAMS_TO_SERVINGS', NULL),
('AGG_PROTEIN_SERVINGS_TO_GRAMS', 'instance_calc', 'CALC_PROTEIN_SERVINGS_TO_GRAMS', NULL),
('AGG_SLEEP_DURATION', 'instance_calc', 'CALC_SLEEP_DURATION', NULL),
('AGG_SLEEP_PERIOD_COUNT', 'instance_calc', 'CALC_SLEEP_PERIOD_COUNT', NULL),
('AGG_SLEEP_PERIOD_DURATION', 'instance_calc', 'CALC_SLEEP_PERIOD_DURATION', NULL),
('AGG_SLEEP_SESSION_COUNT', 'instance_calc', 'CALC_SLEEP_SESSION_COUNT', NULL),
('AGG_STRENGTH_DURATION', 'instance_calc', 'CALC_STRENGTH_DURATION', NULL),
('AGG_STRENGTH_SESSION_COUNT', 'instance_calc', 'CALC_STRENGTH_SESSION_COUNT', NULL),
('AGG_SUNLIGHT_DURATION', 'instance_calc', 'CALC_SUNLIGHT_DURATION', NULL),
('AGG_SUNLIGHT_SESSION_COUNT', 'instance_calc', 'CALC_SUNLIGHT_SESSION_COUNT', NULL),
('AGG_VEGETABLE_TYPE_TO_NUTRITION', 'instance_calc', 'CALC_VEGETABLE_TYPE_TO_NUTRITION', NULL),
('AGG_WAIST_IN_TO_CM', 'instance_calc', 'CALC_WAIST_IN_TO_CM', NULL),
('AGG_WATER_UNIT_CONVERSION', 'instance_calc', 'CALC_WATER_UNIT_CONVERSION', NULL),
('AGG_WEIGHT_KG_TO_LB', 'instance_calc', 'CALC_WEIGHT_KG_TO_LB', NULL),
('AGG_WEIGHT_LB_TO_KG', 'instance_calc', 'CALC_WEIGHT_LB_TO_KG', NULL),
('AGG_WHOLE_GRAIN_TYPE_TO_NUTRITION', 'instance_calc', 'CALC_WHOLE_GRAIN_TYPE_TO_NUTRITION', NULL),
('AGG_ADDED_SUGAR_QUANTITY', 'data_field', NULL, 'DEF_ADDED_SUGAR_QUANTITY'),
('AGG_ALCOHOL_QUANTITY', 'data_field', NULL, 'DEF_ALCOHOL_QUANTITY'),
('AGG_BLOOD_PRESSURE_DIA', 'data_field', NULL, 'DEF_BLOOD_PRESSURE_DIA'),
('AGG_BLOOD_PRESSURE_SYS', 'data_field', NULL, 'DEF_BLOOD_PRESSURE_SYS'),
('AGG_BMI', 'data_field', NULL, 'DEF_BMI'),
('AGG_BMR', 'data_field', NULL, 'DEF_BMR'),
('AGG_BODY_FAT_PCT', 'data_field', NULL, 'DEF_BODY_FAT_PCT'),
('AGG_BRAIN_TRAINING_SESSION_COUNT', 'data_field', NULL, 'DEF_BRAIN_TRAINING_SESSION_COUNT'),
('AGG_CAFFEINE_QUANTITY', 'data_field', NULL, 'DEF_CAFFEINE_QUANTITY'),
('AGG_CALORIES_CONSUMED', 'data_field', NULL, 'DEF_CALORIES_CONSUMED'),
('AGG_CARDIO_CALORIES', 'data_field', NULL, 'DEF_CARDIO_CALORIES'),
('AGG_CARDIO_DISTANCE', 'data_field', NULL, 'DEF_CARDIO_DISTANCE'),
('AGG_CARDIO_DISTANCE_KM', 'data_field', NULL, 'DEF_CARDIO_DISTANCE_KM'),
('AGG_CARDIO_DISTANCE_MILES', 'data_field', NULL, 'DEF_CARDIO_DISTANCE_MILES'),
('AGG_CARDIO_DISTANCE_UNITS', 'data_field', NULL, 'DEF_CARDIO_DISTANCE_UNITS'),
('AGG_CARDIO_INTENSITY', 'data_field', NULL, 'DEF_CARDIO_INTENSITY'),
('AGG_CARDIO_SESSION_COUNT', 'data_field', NULL, 'DEF_CARDIO_SESSION_COUNT'),
('AGG_CIGARETTE_QUANTITY', 'data_field', NULL, 'DEF_CIGARETTE_QUANTITY'),
('AGG_FAT_GRAMS', 'data_field', NULL, 'DEF_FAT_GRAMS'),
('AGG_FAT_SERVINGS', 'data_field', NULL, 'DEF_FAT_SERVINGS'),
('AGG_FIBER_GRAMS', 'data_field', NULL, 'DEF_FIBER_GRAMS'),
('AGG_FIBER_SERVINGS', 'data_field', NULL, 'DEF_FIBER_SERVINGS'),
('AGG_FIBER_SOURCE', 'data_field', NULL, 'DEF_FIBER_SOURCE'),
('AGG_FLEXIBILITY_SESSION_COUNT', 'data_field', NULL, 'DEF_FLEXIBILITY_SESSION_COUNT'),
('AGG_FOCUS_RATING', 'data_field', NULL, 'DEF_FOCUS_RATING'),
('AGG_FOOD_QUANTITY', 'data_field', NULL, 'DEF_FOOD_QUANTITY'),
('AGG_FRUIT_QUANTITY', 'data_field', NULL, 'DEF_FRUIT_QUANTITY'),
('AGG_GRATITUDE_CONTENT', 'data_field', NULL, 'DEF_GRATITUDE_CONTENT'),
('AGG_HIIT_CALORIES', 'data_field', NULL, 'DEF_HIIT_CALORIES'),
('AGG_HIIT_INTENSITY', 'data_field', NULL, 'DEF_HIIT_INTENSITY'),
('AGG_HIIT_SESSION_COUNT', 'data_field', NULL, 'DEF_HIIT_SESSION_COUNT'),
('AGG_HIP_CIRCUMFERENCE', 'data_field', NULL, 'DEF_HIP_CIRCUMFERENCE'),
('AGG_HIP_CM', 'data_field', NULL, 'DEF_HIP_CM'),
('AGG_HIP_IN', 'data_field', NULL, 'DEF_HIP_IN'),
('AGG_HIP_WAIST_RATIO', 'data_field', NULL, 'DEF_HIP_WAIST_RATIO'),
('AGG_JOURNALING_SESSION_COUNT', 'data_field', NULL, 'DEF_JOURNALING_SESSION_COUNT'),
('AGG_LEAN_BODY_MASS', 'data_field', NULL, 'DEF_LEAN_BODY_MASS'),
('AGG_LEGUME_QUANTITY', 'data_field', NULL, 'DEF_LEGUME_QUANTITY'),
('AGG_MEAL_QUALIFIERS', 'data_field', NULL, 'DEF_MEAL_QUALIFIERS'),
('AGG_MEAL_SIZE', 'data_field', NULL, 'DEF_MEAL_SIZE'),
('AGG_MEMORY_CLARITY_RATING', 'data_field', NULL, 'DEF_MEMORY_CLARITY_RATING'),
('AGG_MINDFULNESS_SESSION_COUNT', 'data_field', NULL, 'DEF_MINDFULNESS_SESSION_COUNT'),
('AGG_MOBILITY_CALORIES', 'data_field', NULL, 'DEF_MOBILITY_CALORIES'),
('AGG_MOBILITY_INTENSITY', 'data_field', NULL, 'DEF_MOBILITY_INTENSITY'),
('AGG_MOBILITY_SESSION_COUNT', 'data_field', NULL, 'DEF_MOBILITY_SESSION_COUNT'),
('AGG_MOOD_RATING', 'data_field', NULL, 'DEF_MOOD_RATING'),
('AGG_NECK_CIRCUMFERENCE', 'data_field', NULL, 'DEF_NECK_CIRCUMFERENCE'),
('AGG_NECK_CM', 'data_field', NULL, 'DEF_NECK_CM'),
('AGG_NECK_IN', 'data_field', NULL, 'DEF_NECK_IN'),
('AGG_NUT_SEED_QUANTITY', 'data_field', NULL, 'DEF_NUT_SEED_QUANTITY'),
('AGG_OUTDOOR_SESSION_COUNT', 'data_field', NULL, 'DEF_OUTDOOR_SESSION_COUNT'),
('AGG_PROCESSED_MEAT_QUANTITY', 'data_field', NULL, 'DEF_PROCESSED_MEAT_QUANTITY'),
('AGG_PROTEIN_GRAMS', 'data_field', NULL, 'DEF_PROTEIN_GRAMS'),
('AGG_PROTEIN_SERVINGS', 'data_field', NULL, 'DEF_PROTEIN_SERVINGS'),
('AGG_SCREENING_NAME', 'data_field', NULL, 'DEF_SCREENING_NAME'),
('AGG_SCREENING_RESULT', 'data_field', NULL, 'DEF_SCREENING_RESULT'),
('AGG_SKINCARE_STEP', 'data_field', NULL, 'DEF_SKINCARE_STEP'),
('AGG_SLEEP_BEDTIME', 'data_field', NULL, 'DEF_SLEEP_BEDTIME'),
('AGG_SLEEP_FACTORS', 'data_field', NULL, 'DEF_SLEEP_FACTORS'),
('AGG_SLEEP_PERIOD_COUNT', 'data_field', NULL, 'DEF_SLEEP_PERIOD_COUNT'),
('AGG_SLEEP_QUALITY', 'data_field', NULL, 'DEF_SLEEP_QUALITY'),
('AGG_SLEEP_SESSION_COUNT', 'data_field', NULL, 'DEF_SLEEP_SESSION_COUNT'),
('AGG_SLEEP_WAKETIME', 'data_field', NULL, 'DEF_SLEEP_WAKETIME'),
('AGG_STEPS', 'data_field', NULL, 'DEF_STEPS'),
('AGG_STRENGTH_CALORIES', 'data_field', NULL, 'DEF_STRENGTH_CALORIES'),
('AGG_STRENGTH_INTENSITY', 'data_field', NULL, 'DEF_STRENGTH_INTENSITY'),
('AGG_STRENGTH_MUSCLE_GROUPS', 'data_field', NULL, 'DEF_STRENGTH_MUSCLE_GROUPS'),
('AGG_STRENGTH_SESSION_COUNT', 'data_field', NULL, 'DEF_STRENGTH_SESSION_COUNT'),
('AGG_STRESS_FACTORS', 'data_field', NULL, 'DEF_STRESS_FACTORS'),
('AGG_STRESS_LEVEL', 'data_field', NULL, 'DEF_STRESS_LEVEL'),
('AGG_SUBSTANCE_SOURCE', 'data_field', NULL, 'DEF_SUBSTANCE_SOURCE'),
('AGG_SUBSTANCE_USAGE_LEVEL', 'data_field', NULL, 'DEF_SUBSTANCE_USAGE_LEVEL'),
('AGG_SUNLIGHT_SESSION_COUNT', 'data_field', NULL, 'DEF_SUNLIGHT_SESSION_COUNT'),
('AGG_THERAPEUTIC_DOSE', 'data_field', NULL, 'DEF_THERAPEUTIC_DOSE'),
('AGG_THERAPEUTIC_UNITS', 'data_field', NULL, 'DEF_THERAPEUTIC_UNITS'),
('AGG_ULTRA_PROCESSED_QUANTITY', 'data_field', NULL, 'DEF_ULTRA_PROCESSED_QUANTITY'),
('AGG_UNHEALTHY_BEV_QUANTITY', 'data_field', NULL, 'DEF_UNHEALTHY_BEV_QUANTITY'),
('AGG_VEGETABLE_QUANTITY', 'data_field', NULL, 'DEF_VEGETABLE_QUANTITY'),
('AGG_WAIST_CIRCUMFERENCE', 'data_field', NULL, 'DEF_WAIST_CIRCUMFERENCE'),
('AGG_WAIST_CM', 'data_field', NULL, 'DEF_WAIST_CM'),
('AGG_WAIST_IN', 'data_field', NULL, 'DEF_WAIST_IN'),
('AGG_WATER_QUANTITY', 'data_field', NULL, 'DEF_WATER_QUANTITY'),
('AGG_WATER_UNITS', 'data_field', NULL, 'DEF_WATER_UNITS'),
('AGG_WEIGHT', 'data_field', NULL, 'DEF_WEIGHT'),
('AGG_WEIGHT_KG', 'data_field', NULL, 'DEF_WEIGHT_KG'),
('AGG_WEIGHT_LB', 'data_field', NULL, 'DEF_WEIGHT_LB'),
('AGG_WHOLE_GRAIN_QUANTITY', 'data_field', NULL, 'DEF_WHOLE_GRAIN_QUANTITY');


-- =====================================================
-- Summary
-- =====================================================

DO $$
DECLARE
  dep_count INT;
BEGIN
  SELECT COUNT(*) INTO dep_count FROM aggregation_metrics_dependencies;

  RAISE NOTICE '✅ Aggregation Dependencies Created';
  RAISE NOTICE '';
  RAISE NOTICE 'Total dependencies: %', dep_count;
  RAISE NOTICE '';
  RAISE NOTICE 'Next: Verify aggregation pipeline can process these';
END $$;

COMMIT;
