-- =====================================================
-- Create Missing Aggregation Metrics
-- =====================================================
-- AGG_* metrics that have corresponding CALC_* or DEF_* sources
--
-- Created: 2025-10-22
-- =====================================================

BEGIN;

-- =====================================================
-- PART 1: Create Aggregation Metrics
-- =====================================================

INSERT INTO aggregation_metrics (agg_id, metric_name, display_name, description, output_unit, is_active)
VALUES
('AGG_ADDED_SUGAR_QUANTITY', 'added_sugar_quantity', 'Added Sugar Quantity', 'Aggregated added sugar quantity', 'serving', true),
('AGG_ALCOHOL_QUANTITY', 'alcohol_quantity', 'Alcohol Quantity', 'Aggregated alcohol quantity', 'drink', true),
('AGG_BLOOD_PRESSURE_DIA', 'blood_pressure_dia', 'Blood Pressure Dia', 'Aggregated blood pressure dia', 'millimeters_mercury', true),
('AGG_BLOOD_PRESSURE_SYS', 'blood_pressure_sys', 'Blood Pressure Sys', 'Aggregated blood pressure sys', 'millimeters_mercury', true),
('AGG_BMR', 'bmr', 'Bmr', 'Aggregated bmr', 'kilocalorie', true),
('AGG_BODY_FAT_PCT', 'body_fat_pct', 'Body Fat Pct', 'Aggregated body fat pct', 'percent', true),
('AGG_BRAIN_TRAINING_SESSION_COUNT', 'brain_training_session_count', 'Brain Training Session Count', 'Aggregated brain training session count', 'count', true),
('AGG_CAFFEINE_QUANTITY', 'caffeine_quantity', 'Caffeine Quantity', 'Aggregated caffeine quantity', 'milligram', true),
('AGG_CALORIES_CONSUMED', 'calories_consumed', 'Calories Consumed', 'Aggregated calories consumed', 'kilocalorie', true),
('AGG_CARDIO_CALORIES', 'cardio_calories', 'Cardio Calories', 'Aggregated cardio calories', 'kilocalorie', true),
('AGG_CARDIO_DISTANCE', 'cardio_distance', 'Cardio Distance', 'Aggregated cardio distance', 'count', true),
('AGG_CARDIO_DISTANCE_KM', 'cardio_distance_km', 'Cardio Distance Km', 'Aggregated cardio distance km', 'kilometer', true),
('AGG_CARDIO_DISTANCE_MILES', 'cardio_distance_miles', 'Cardio Distance Miles', 'Aggregated cardio distance miles', 'mile', true),
('AGG_CARDIO_DISTANCE_UNITS', 'cardio_distance_units', 'Cardio Distance Units', 'Aggregated cardio distance units', 'count', true),
('AGG_CARDIO_INTENSITY', 'cardio_intensity', 'Cardio Intensity', 'Aggregated cardio intensity', 'scale_1_10', true),
('AGG_CIGARETTE_QUANTITY', 'cigarette_quantity', 'Cigarette Quantity', 'Aggregated cigarette quantity', 'count', true),
('AGG_DISTANCE_KM_TO_MILES', 'distance_km_to_miles', 'Distance Km To Miles', 'Aggregated distance km to miles', 'mile', true),
('AGG_DISTANCE_MILES_TO_KM', 'distance_miles_to_km', 'Distance Miles To Km', 'Aggregated distance miles to km', 'kilometer', true),
('AGG_FAT_GRAMS', 'fat_grams', 'Fat Grams', 'Aggregated fat grams', 'gram', true),
('AGG_FAT_GRAMS_TO_SERVINGS', 'fat_grams_to_servings', 'Fat Grams To Servings', 'Aggregated fat grams to servings', 'serving', true),
('AGG_FAT_SERVINGS', 'fat_servings', 'Fat Servings', 'Aggregated fat servings', 'serving', true),
('AGG_FAT_SERVINGS_TO_GRAMS', 'fat_servings_to_grams', 'Fat Servings To Grams', 'Aggregated fat servings to grams', 'gram', true),
('AGG_FIBER_GRAMS_TO_SERVINGS', 'fiber_grams_to_servings', 'Fiber Grams To Servings', 'Aggregated fiber grams to servings', 'serving', true),
('AGG_FIBER_SERVINGS_TO_GRAMS', 'fiber_servings_to_grams', 'Fiber Servings To Grams', 'Aggregated fiber servings to grams', 'gram', true),
('AGG_FIBER_SOURCE', 'fiber_source', 'Fiber Source', 'Aggregated fiber source', 'count', true),
('AGG_FLEXIBILITY_SESSION_COUNT', 'flexibility_session_count', 'Flexibility Session Count', 'Aggregated flexibility session count', 'count', true),
('AGG_FOOD_QUANTITY', 'food_quantity', 'Food Quantity', 'Aggregated food quantity', 'count', true),
('AGG_FRUIT_QUANTITY', 'fruit_quantity', 'Fruit Quantity', 'Aggregated fruit quantity', 'serving', true),
('AGG_FRUIT_TYPE_TO_NUTRITION', 'fruit_type_to_nutrition', 'Fruit Type To Nutrition', 'Aggregated fruit type to nutrition', 'count', true),
('AGG_GRATITUDE_CONTENT', 'gratitude_content', 'Gratitude Content', 'Aggregated gratitude content', 'count', true),
('AGG_HIIT_CALORIES', 'hiit_calories', 'Hiit Calories', 'Aggregated hiit calories', 'kilocalorie', true),
('AGG_HIIT_INTENSITY', 'hiit_intensity', 'Hiit Intensity', 'Aggregated hiit intensity', 'scale_1_5', true),
('AGG_HIIT_SESSION_COUNT', 'hiit_session_count', 'Hiit Session Count', 'Aggregated hiit session count', 'count', true),
('AGG_HIP_CIRCUMFERENCE', 'hip_circumference', 'Hip Circumference', 'Aggregated hip circumference', 'centimeter', true),
('AGG_HIP_CM', 'hip_cm', 'Hip Cm', 'Aggregated hip cm', 'centimeter', true),
('AGG_HIP_IN', 'hip_in', 'Hip In', 'Aggregated hip in', 'inch', true),
('AGG_HIP_IN_TO_CM', 'hip_in_to_cm', 'Hip In To Cm', 'Aggregated hip in to cm', 'centimeter', true),
('AGG_HIP_WAIST_RATIO', 'hip_waist_ratio', 'Hip Waist Ratio', 'Aggregated hip waist ratio', 'count', true),
('AGG_JOURNALING_DURATION', 'journaling_duration', 'Journaling Duration', 'Aggregated journaling duration', 'minute', true),
('AGG_JOURNALING_SESSION_COUNT', 'journaling_session_count', 'Journaling Session Count', 'Aggregated journaling session count', 'count', true),
('AGG_LEAN_BODY_MASS', 'lean_body_mass', 'Lean Body Mass', 'Aggregated lean body mass', 'kilogram', true),
('AGG_LEGUME_QUANTITY', 'legume_quantity', 'Legume Quantity', 'Aggregated legume quantity', 'serving', true),
('AGG_LEGUME_TYPE_TO_NUTRITION', 'legume_type_to_nutrition', 'Legume Type To Nutrition', 'Aggregated legume type to nutrition', 'count', true),
('AGG_MEAL_QUALIFIERS', 'meal_qualifiers', 'Meal Qualifiers', 'Aggregated meal qualifiers', 'count', true),
('AGG_MEAL_SIZE', 'meal_size', 'Meal Size', 'Aggregated meal size', 'count', true),
('AGG_MINDFULNESS_SESSION_COUNT', 'mindfulness_session_count', 'Mindfulness Session Count', 'Aggregated mindfulness session count', 'count', true),
('AGG_MOBILITY_CALORIES', 'mobility_calories', 'Mobility Calories', 'Aggregated mobility calories', 'kilocalorie', true),
('AGG_MOBILITY_INTENSITY', 'mobility_intensity', 'Mobility Intensity', 'Aggregated mobility intensity', 'scale_1_5', true),
('AGG_MOBILITY_SESSION_COUNT', 'mobility_session_count', 'Mobility Session Count', 'Aggregated mobility session count', 'count', true),
('AGG_NECK_CIRCUMFERENCE', 'neck_circumference', 'Neck Circumference', 'Aggregated neck circumference', 'centimeter', true),
('AGG_NECK_CM', 'neck_cm', 'Neck Cm', 'Aggregated neck cm', 'centimeter', true),
('AGG_NECK_IN', 'neck_in', 'Neck In', 'Aggregated neck in', 'inch', true),
('AGG_NECK_IN_TO_CM', 'neck_in_to_cm', 'Neck In To Cm', 'Aggregated neck in to cm', 'centimeter', true),
('AGG_NUT_SEED_QUANTITY', 'nut_seed_quantity', 'Nut Seed Quantity', 'Aggregated nut seed quantity', 'serving', true),
('AGG_NUT_SEED_TYPE_TO_NUTRITION', 'nut_seed_type_to_nutrition', 'Nut Seed Type To Nutrition', 'Aggregated nut seed type to nutrition', 'count', true),
('AGG_OUTDOOR_DURATION', 'outdoor_duration', 'Outdoor Duration', 'Aggregated outdoor duration', 'minute', true),
('AGG_OUTDOOR_SESSION_COUNT', 'outdoor_session_count', 'Outdoor Session Count', 'Aggregated outdoor session count', 'count', true),
('AGG_PROCESSED_MEAT_QUANTITY', 'processed_meat_quantity', 'Processed Meat Quantity', 'Aggregated processed meat quantity', 'serving', true),
('AGG_PROTEIN_GRAMS_TO_SERVINGS', 'protein_grams_to_servings', 'Protein Grams To Servings', 'Aggregated protein grams to servings', 'serving', true),
('AGG_PROTEIN_SERVINGS_TO_GRAMS', 'protein_servings_to_grams', 'Protein Servings To Grams', 'Aggregated protein servings to grams', 'gram', true),
('AGG_SCREENING_NAME', 'screening_name', 'Screening Name', 'Aggregated screening name', 'count', true),
('AGG_SCREENING_RESULT', 'screening_result', 'Screening Result', 'Aggregated screening result', 'count', true),
('AGG_SKINCARE_STEP', 'skincare_step', 'Skincare Step', 'Aggregated skincare step', 'count', true),
('AGG_SLEEP_BEDTIME', 'sleep_bedtime', 'Sleep Bedtime', 'Aggregated sleep bedtime', 'datetime_combined', true),
('AGG_SLEEP_FACTORS', 'sleep_factors', 'Sleep Factors', 'Aggregated sleep factors', 'count', true),
('AGG_SLEEP_PERIOD_COUNT', 'sleep_period_count', 'Sleep Period Count', 'Aggregated sleep period count', 'count', true),
('AGG_SLEEP_PERIOD_DURATION', 'sleep_period_duration', 'Sleep Period Duration', 'Aggregated sleep period duration', 'minute', true),
('AGG_SLEEP_QUALITY', 'sleep_quality', 'Sleep Quality', 'Aggregated sleep quality', 'count', true),
('AGG_SLEEP_WAKETIME', 'sleep_waketime', 'Sleep Waketime', 'Aggregated sleep waketime', 'datetime_combined', true),
('AGG_STRENGTH_CALORIES', 'strength_calories', 'Strength Calories', 'Aggregated strength calories', 'kilocalorie', true),
('AGG_STRENGTH_DURATION', 'strength_duration', 'Strength Duration', 'Aggregated strength duration', 'minute', true),
('AGG_STRENGTH_INTENSITY', 'strength_intensity', 'Strength Intensity', 'Aggregated strength intensity', 'count', true),
('AGG_STRENGTH_MUSCLE_GROUPS', 'strength_muscle_groups', 'Strength Muscle Groups', 'Aggregated strength muscle groups', 'count', true),
('AGG_STRESS_FACTORS', 'stress_factors', 'Stress Factors', 'Aggregated stress factors', 'count', true),
('AGG_STRESS_LEVEL', 'stress_level', 'Stress Level', 'Aggregated stress level', 'count', true),
('AGG_SUBSTANCE_SOURCE', 'substance_source', 'Substance Source', 'Aggregated substance source', 'count', true),
('AGG_SUBSTANCE_USAGE_LEVEL', 'substance_usage_level', 'Substance Usage Level', 'Aggregated substance usage level', 'count', true),
('AGG_SUNLIGHT_DURATION', 'sunlight_duration', 'Sunlight Duration', 'Aggregated sunlight duration', 'minute', true),
('AGG_SUNLIGHT_SESSION_COUNT', 'sunlight_session_count', 'Sunlight Session Count', 'Aggregated sunlight session count', 'count', true),
('AGG_THERAPEUTIC_DOSE', 'therapeutic_dose', 'Therapeutic Dose', 'Aggregated therapeutic dose', 'count', true),
('AGG_THERAPEUTIC_UNITS', 'therapeutic_units', 'Therapeutic Units', 'Aggregated therapeutic units', 'count', true),
('AGG_ULTRA_PROCESSED_QUANTITY', 'ultra_processed_quantity', 'Ultra Processed Quantity', 'Aggregated ultra processed quantity', 'serving', true),
('AGG_UNHEALTHY_BEV_QUANTITY', 'unhealthy_bev_quantity', 'Unhealthy Bev Quantity', 'Aggregated unhealthy bev quantity', 'serving', true),
('AGG_VEGETABLE_QUANTITY', 'vegetable_quantity', 'Vegetable Quantity', 'Aggregated vegetable quantity', 'serving', true),
('AGG_VEGETABLE_TYPE_TO_NUTRITION', 'vegetable_type_to_nutrition', 'Vegetable Type To Nutrition', 'Aggregated vegetable type to nutrition', 'count', true),
('AGG_WAIST_CIRCUMFERENCE', 'waist_circumference', 'Waist Circumference', 'Aggregated waist circumference', 'centimeter', true),
('AGG_WAIST_CM', 'waist_cm', 'Waist Cm', 'Aggregated waist cm', 'centimeter', true),
('AGG_WAIST_IN', 'waist_in', 'Waist In', 'Aggregated waist in', 'inch', true),
('AGG_WAIST_IN_TO_CM', 'waist_in_to_cm', 'Waist In To Cm', 'Aggregated waist in to cm', 'centimeter', true),
('AGG_WATER_QUANTITY', 'water_quantity', 'Water Quantity', 'Aggregated water quantity', 'count', true),
('AGG_WATER_UNITS', 'water_units', 'Water Units', 'Aggregated water units', 'count', true),
('AGG_WATER_UNIT_CONVERSION', 'water_unit_conversion', 'Water Unit Conversion', 'Aggregated water unit conversion', 'count', true),
('AGG_WEIGHT', 'weight', 'Weight', 'Aggregated weight', 'kilogram', true),
('AGG_WEIGHT_KG', 'weight_kg', 'Weight Kg', 'Aggregated weight kg', 'kilogram', true),
('AGG_WEIGHT_KG_TO_LB', 'weight_kg_to_lb', 'Weight Kg To Lb', 'Aggregated weight kg to lb', 'pound', true),
('AGG_WEIGHT_LB', 'weight_lb', 'Weight Lb', 'Aggregated weight lb', 'pound', true),
('AGG_WEIGHT_LB_TO_KG', 'weight_lb_to_kg', 'Weight Lb To Kg', 'Aggregated weight lb to kg', 'kilogram', true),
('AGG_WHOLE_GRAIN_QUANTITY', 'whole_grain_quantity', 'Whole Grain Quantity', 'Aggregated whole grain quantity', 'serving', true),
('AGG_WHOLE_GRAIN_TYPE_TO_NUTRITION', 'whole_grain_type_to_nutrition', 'Whole Grain Type To Nutrition', 'Aggregated whole grain type to nutrition', 'count', true);


-- =====================================================
-- PART 2: Create Aggregation Metrics Periods Config
-- =====================================================

INSERT INTO aggregation_metrics_periods (agg_metric_id, period_id, chart_type, x_axis_type, x_axis_granularity, bars, days, y_axis_min, y_axis_max, y_axis_label, y_axis_auto_scale)
VALUES
('AGG_ADDED_SUGAR_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_ADDED_SUGAR_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_ADDED_SUGAR_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_ALCOHOL_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'drink', true),
('AGG_ALCOHOL_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'drink', true),
('AGG_ALCOHOL_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'drink', true),
('AGG_BLOOD_PRESSURE_DIA', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'millimeters_mercury', true),
('AGG_BLOOD_PRESSURE_DIA', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'millimeters_mercury', true),
('AGG_BLOOD_PRESSURE_DIA', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'millimeters_mercury', true),
('AGG_BLOOD_PRESSURE_SYS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'millimeters_mercury', true),
('AGG_BLOOD_PRESSURE_SYS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'millimeters_mercury', true),
('AGG_BLOOD_PRESSURE_SYS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'millimeters_mercury', true),
('AGG_BMR', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilocalorie', true),
('AGG_BMR', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilocalorie', true),
('AGG_BMR', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilocalorie', true),
('AGG_BODY_FAT_PCT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'percent', true),
('AGG_BODY_FAT_PCT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'percent', true),
('AGG_BODY_FAT_PCT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'percent', true),
('AGG_BRAIN_TRAINING_SESSION_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_BRAIN_TRAINING_SESSION_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_BRAIN_TRAINING_SESSION_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_CAFFEINE_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'milligram', true),
('AGG_CAFFEINE_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'milligram', true),
('AGG_CAFFEINE_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'milligram', true),
('AGG_CALORIES_CONSUMED', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilocalorie', true),
('AGG_CALORIES_CONSUMED', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilocalorie', true),
('AGG_CALORIES_CONSUMED', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilocalorie', true),
('AGG_CARDIO_CALORIES', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilocalorie', true),
('AGG_CARDIO_CALORIES', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilocalorie', true),
('AGG_CARDIO_CALORIES', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilocalorie', true),
('AGG_CARDIO_DISTANCE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_CARDIO_DISTANCE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_CARDIO_DISTANCE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_CARDIO_DISTANCE_KM', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilometer', true),
('AGG_CARDIO_DISTANCE_KM', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilometer', true),
('AGG_CARDIO_DISTANCE_KM', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilometer', true),
('AGG_CARDIO_DISTANCE_MILES', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'mile', true),
('AGG_CARDIO_DISTANCE_MILES', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'mile', true),
('AGG_CARDIO_DISTANCE_MILES', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'mile', true),
('AGG_CARDIO_DISTANCE_UNITS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_CARDIO_DISTANCE_UNITS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_CARDIO_DISTANCE_UNITS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_CARDIO_INTENSITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'scale_1_10', true),
('AGG_CARDIO_INTENSITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'scale_1_10', true),
('AGG_CARDIO_INTENSITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'scale_1_10', true),
('AGG_CIGARETTE_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_CIGARETTE_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_CIGARETTE_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_DISTANCE_KM_TO_MILES', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'mile', true),
('AGG_DISTANCE_KM_TO_MILES', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'mile', true),
('AGG_DISTANCE_KM_TO_MILES', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'mile', true),
('AGG_DISTANCE_MILES_TO_KM', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilometer', true),
('AGG_DISTANCE_MILES_TO_KM', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilometer', true),
('AGG_DISTANCE_MILES_TO_KM', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilometer', true),
('AGG_FAT_GRAMS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'gram', true),
('AGG_FAT_GRAMS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'gram', true),
('AGG_FAT_GRAMS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'gram', true),
('AGG_FAT_GRAMS_TO_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_FAT_GRAMS_TO_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_FAT_GRAMS_TO_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_FAT_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_FAT_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_FAT_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_FAT_SERVINGS_TO_GRAMS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'gram', true),
('AGG_FAT_SERVINGS_TO_GRAMS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'gram', true),
('AGG_FAT_SERVINGS_TO_GRAMS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'gram', true),
('AGG_FIBER_GRAMS_TO_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_FIBER_GRAMS_TO_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_FIBER_GRAMS_TO_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_FIBER_SERVINGS_TO_GRAMS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'gram', true),
('AGG_FIBER_SERVINGS_TO_GRAMS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'gram', true),
('AGG_FIBER_SERVINGS_TO_GRAMS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'gram', true),
('AGG_FIBER_SOURCE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_FIBER_SOURCE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_FIBER_SOURCE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_FLEXIBILITY_SESSION_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_FLEXIBILITY_SESSION_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_FLEXIBILITY_SESSION_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_FOOD_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_FOOD_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_FOOD_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_FRUIT_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_FRUIT_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_FRUIT_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_FRUIT_TYPE_TO_NUTRITION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_FRUIT_TYPE_TO_NUTRITION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_FRUIT_TYPE_TO_NUTRITION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_GRATITUDE_CONTENT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_GRATITUDE_CONTENT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_GRATITUDE_CONTENT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_HIIT_CALORIES', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilocalorie', true),
('AGG_HIIT_CALORIES', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilocalorie', true),
('AGG_HIIT_CALORIES', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilocalorie', true),
('AGG_HIIT_INTENSITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'scale_1_5', true),
('AGG_HIIT_INTENSITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'scale_1_5', true),
('AGG_HIIT_INTENSITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'scale_1_5', true),
('AGG_HIIT_SESSION_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_HIIT_SESSION_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_HIIT_SESSION_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_HIP_CIRCUMFERENCE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_HIP_CIRCUMFERENCE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_HIP_CIRCUMFERENCE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_HIP_CM', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_HIP_CM', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_HIP_CM', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_HIP_IN', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'inch', true),
('AGG_HIP_IN', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'inch', true),
('AGG_HIP_IN', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'inch', true),
('AGG_HIP_IN_TO_CM', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_HIP_IN_TO_CM', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_HIP_IN_TO_CM', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_HIP_WAIST_RATIO', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_HIP_WAIST_RATIO', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_HIP_WAIST_RATIO', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_JOURNALING_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minute', true),
('AGG_JOURNALING_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minute', true),
('AGG_JOURNALING_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minute', true),
('AGG_JOURNALING_SESSION_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_JOURNALING_SESSION_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_JOURNALING_SESSION_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_LEAN_BODY_MASS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilogram', true),
('AGG_LEAN_BODY_MASS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilogram', true),
('AGG_LEAN_BODY_MASS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilogram', true),
('AGG_LEGUME_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_LEGUME_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_LEGUME_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_LEGUME_TYPE_TO_NUTRITION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_LEGUME_TYPE_TO_NUTRITION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_LEGUME_TYPE_TO_NUTRITION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_MEAL_QUALIFIERS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_MEAL_QUALIFIERS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_MEAL_QUALIFIERS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_MEAL_SIZE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_MEAL_SIZE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_MEAL_SIZE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_MINDFULNESS_SESSION_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_MINDFULNESS_SESSION_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_MINDFULNESS_SESSION_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_MOBILITY_CALORIES', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilocalorie', true),
('AGG_MOBILITY_CALORIES', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilocalorie', true),
('AGG_MOBILITY_CALORIES', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilocalorie', true),
('AGG_MOBILITY_INTENSITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'scale_1_5', true),
('AGG_MOBILITY_INTENSITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'scale_1_5', true),
('AGG_MOBILITY_INTENSITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'scale_1_5', true),
('AGG_MOBILITY_SESSION_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_MOBILITY_SESSION_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_MOBILITY_SESSION_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_NECK_CIRCUMFERENCE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_NECK_CIRCUMFERENCE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_NECK_CIRCUMFERENCE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_NECK_CM', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_NECK_CM', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_NECK_CM', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_NECK_IN', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'inch', true),
('AGG_NECK_IN', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'inch', true),
('AGG_NECK_IN', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'inch', true),
('AGG_NECK_IN_TO_CM', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_NECK_IN_TO_CM', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_NECK_IN_TO_CM', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_NUT_SEED_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_NUT_SEED_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_NUT_SEED_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_NUT_SEED_TYPE_TO_NUTRITION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_NUT_SEED_TYPE_TO_NUTRITION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_NUT_SEED_TYPE_TO_NUTRITION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_OUTDOOR_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minute', true),
('AGG_OUTDOOR_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minute', true),
('AGG_OUTDOOR_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minute', true),
('AGG_OUTDOOR_SESSION_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_OUTDOOR_SESSION_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_OUTDOOR_SESSION_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_PROCESSED_MEAT_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_PROCESSED_MEAT_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_PROCESSED_MEAT_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_PROTEIN_GRAMS_TO_SERVINGS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_PROTEIN_GRAMS_TO_SERVINGS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_PROTEIN_GRAMS_TO_SERVINGS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_PROTEIN_SERVINGS_TO_GRAMS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'gram', true),
('AGG_PROTEIN_SERVINGS_TO_GRAMS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'gram', true),
('AGG_PROTEIN_SERVINGS_TO_GRAMS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'gram', true),
('AGG_SCREENING_NAME', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SCREENING_NAME', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SCREENING_NAME', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SCREENING_RESULT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SCREENING_RESULT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SCREENING_RESULT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SKINCARE_STEP', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SKINCARE_STEP', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SKINCARE_STEP', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SLEEP_BEDTIME', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'datetime_combined', true),
('AGG_SLEEP_BEDTIME', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'datetime_combined', true),
('AGG_SLEEP_BEDTIME', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'datetime_combined', true),
('AGG_SLEEP_FACTORS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SLEEP_FACTORS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SLEEP_FACTORS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SLEEP_PERIOD_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_SLEEP_PERIOD_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_SLEEP_PERIOD_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_SLEEP_PERIOD_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minute', true),
('AGG_SLEEP_PERIOD_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minute', true),
('AGG_SLEEP_PERIOD_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minute', true),
('AGG_SLEEP_QUALITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SLEEP_QUALITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SLEEP_QUALITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SLEEP_WAKETIME', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'datetime_combined', true),
('AGG_SLEEP_WAKETIME', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'datetime_combined', true),
('AGG_SLEEP_WAKETIME', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'datetime_combined', true),
('AGG_STRENGTH_CALORIES', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilocalorie', true),
('AGG_STRENGTH_CALORIES', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilocalorie', true),
('AGG_STRENGTH_CALORIES', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilocalorie', true),
('AGG_STRENGTH_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minute', true),
('AGG_STRENGTH_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minute', true),
('AGG_STRENGTH_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minute', true),
('AGG_STRENGTH_INTENSITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_STRENGTH_INTENSITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_STRENGTH_INTENSITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_STRENGTH_MUSCLE_GROUPS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_STRENGTH_MUSCLE_GROUPS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_STRENGTH_MUSCLE_GROUPS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_STRESS_FACTORS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_STRESS_FACTORS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_STRESS_FACTORS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_STRESS_LEVEL', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_STRESS_LEVEL', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_STRESS_LEVEL', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SUBSTANCE_SOURCE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SUBSTANCE_SOURCE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SUBSTANCE_SOURCE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SUBSTANCE_USAGE_LEVEL', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_SUBSTANCE_USAGE_LEVEL', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_SUBSTANCE_USAGE_LEVEL', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_SUNLIGHT_DURATION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 120, 'minute', true),
('AGG_SUNLIGHT_DURATION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 120, 'minute', true),
('AGG_SUNLIGHT_DURATION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 120, 'minute', true),
('AGG_SUNLIGHT_SESSION_COUNT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 10, 'count', true),
('AGG_SUNLIGHT_SESSION_COUNT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 10, 'count', true),
('AGG_SUNLIGHT_SESSION_COUNT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 10, 'count', true),
('AGG_THERAPEUTIC_DOSE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_THERAPEUTIC_DOSE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_THERAPEUTIC_DOSE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_THERAPEUTIC_UNITS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_THERAPEUTIC_UNITS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_THERAPEUTIC_UNITS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_ULTRA_PROCESSED_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_ULTRA_PROCESSED_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_ULTRA_PROCESSED_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_UNHEALTHY_BEV_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_UNHEALTHY_BEV_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_UNHEALTHY_BEV_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_VEGETABLE_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_VEGETABLE_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_VEGETABLE_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_VEGETABLE_TYPE_TO_NUTRITION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_VEGETABLE_TYPE_TO_NUTRITION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_VEGETABLE_TYPE_TO_NUTRITION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_WAIST_CIRCUMFERENCE', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_WAIST_CIRCUMFERENCE', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_WAIST_CIRCUMFERENCE', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_WAIST_CM', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_WAIST_CM', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_WAIST_CM', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_WAIST_IN', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'inch', true),
('AGG_WAIST_IN', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'inch', true),
('AGG_WAIST_IN', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'inch', true),
('AGG_WAIST_IN_TO_CM', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'centimeter', true),
('AGG_WAIST_IN_TO_CM', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'centimeter', true),
('AGG_WAIST_IN_TO_CM', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'centimeter', true),
('AGG_WATER_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_WATER_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_WATER_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_WATER_UNITS', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_WATER_UNITS', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_WATER_UNITS', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_WATER_UNIT_CONVERSION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_WATER_UNIT_CONVERSION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_WATER_UNIT_CONVERSION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true),
('AGG_WEIGHT', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilogram', true),
('AGG_WEIGHT', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilogram', true),
('AGG_WEIGHT', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilogram', true),
('AGG_WEIGHT_KG', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilogram', true),
('AGG_WEIGHT_KG', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilogram', true),
('AGG_WEIGHT_KG', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilogram', true),
('AGG_WEIGHT_KG_TO_LB', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'pound', true),
('AGG_WEIGHT_KG_TO_LB', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'pound', true),
('AGG_WEIGHT_KG_TO_LB', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'pound', true),
('AGG_WEIGHT_LB', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'pound', true),
('AGG_WEIGHT_LB', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'pound', true),
('AGG_WEIGHT_LB', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'pound', true),
('AGG_WEIGHT_LB_TO_KG', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'kilogram', true),
('AGG_WEIGHT_LB_TO_KG', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'kilogram', true),
('AGG_WEIGHT_LB_TO_KG', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'kilogram', true),
('AGG_WHOLE_GRAIN_QUANTITY', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'serving', true),
('AGG_WHOLE_GRAIN_QUANTITY', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'serving', true),
('AGG_WHOLE_GRAIN_QUANTITY', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'serving', true),
('AGG_WHOLE_GRAIN_TYPE_TO_NUTRITION', 'daily', 'bar_vertical', 'date', 'hour', 24, 1, 0, 100, 'count', true),
('AGG_WHOLE_GRAIN_TYPE_TO_NUTRITION', 'weekly', 'bar_vertical', 'date', 'day', 7, 7, 0, 100, 'count', true),
('AGG_WHOLE_GRAIN_TYPE_TO_NUTRITION', 'monthly', 'bar_vertical', 'date', 'day', 33, 33, 0, 100, 'count', true);


-- =====================================================
-- Summary
-- =====================================================

DO $$
DECLARE
  agg_count INT;
  period_count INT;
BEGIN
  SELECT COUNT(*) INTO agg_count FROM aggregation_metrics;
  SELECT COUNT(*) INTO period_count FROM aggregation_metrics_periods;

  RAISE NOTICE '✅ Missing Aggregation Metrics Created';
  RAISE NOTICE '';
  RAISE NOTICE 'Total aggregation_metrics: %', agg_count;
  RAISE NOTICE 'Total aggregation_metrics_periods: %', period_count;
END $$;

COMMIT;
