-- =====================================================
-- Create Display Screens
-- =====================================================
-- Organize display_metrics into categorical screens
--
-- Created: 2025-10-22
-- =====================================================

BEGIN;

-- Delete existing screens
DELETE FROM display_screens_display_metrics;
DELETE FROM display_screens;

-- =====================================================
-- PART 1: Create Display Screens
-- =====================================================

INSERT INTO display_screens
(screen_id, name, overview, pillar, icon, default_time_period, layout_type, screen_type, display_order, is_active)
VALUES
('SCREEN_SLEEP', 'Sleep Overview', 'Track your sleep duration, quality, stages, and consistency', 'Restorative Sleep', '🛌', 'weekly', 'detailed', 'summary', 1, true),
('SCREEN_CARDIO', 'Cardio Activity', 'Monitor your cardiovascular exercise sessions, duration, and intensity', 'Movement + Exercise', '🏃', 'weekly', 'detailed', 'summary', 2, true),
('SCREEN_STRENGTH', 'Strength Training', 'Track your strength training sessions and duration', 'Movement + Exercise', '💪', 'weekly', 'detailed', 'summary', 3, true),
('SCREEN_HIIT', 'HIIT & Mobility', 'Track HIIT workouts and mobility sessions', 'Movement + Exercise', '⚡', 'weekly', 'detailed', 'summary', 4, true),
('SCREEN_ACTIVITY', 'Daily Activity', 'Monitor steps, walking, and overall activity', 'Movement + Exercise', '🚶', 'weekly', 'detailed', 'summary', 5, true),
('SCREEN_PROTEIN', 'Protein Intake', 'Track protein grams, servings, and variety', 'Healthful Nutrition', '🥩', 'weekly', 'detailed', 'summary', 6, true),
('SCREEN_VEGETABLES', 'Vegetables', 'Monitor vegetable servings and variety', 'Healthful Nutrition', '🥗', 'weekly', 'detailed', 'summary', 7, true),
('SCREEN_FRUITS', 'Fruits', 'Track fruit servings and variety', 'Healthful Nutrition', '🍎', 'weekly', 'detailed', 'summary', 8, true),
('SCREEN_FIBER', 'Fiber & Whole Grains', 'Monitor fiber intake and whole grain variety', 'Healthful Nutrition', '🌾', 'weekly', 'detailed', 'summary', 9, true),
('SCREEN_HYDRATION', 'Hydration', 'Track water consumption', 'Healthful Nutrition', '💧', 'weekly', 'detailed', 'summary', 10, true),
('SCREEN_MEAL_TIMING', 'Meal Timing', 'Track meal times, eating window, and fasting', 'Healthful Nutrition', '⏰', 'weekly', 'detailed', 'summary', 11, true),
('SCREEN_NUTRITION_QUALITY', 'Nutrition Quality', 'Monitor processed foods, added sugar, and healthy fats', 'Healthful Nutrition', '🍽️', 'weekly', 'detailed', 'summary', 12, true),
('SCREEN_MINDFULNESS', 'Mindfulness & Meditation', 'Track meditation, mindfulness, and breathwork', 'Stress Management', '🧘', 'weekly', 'detailed', 'summary', 13, true),
('SCREEN_COGNITIVE', 'Cognitive Health', 'Track brain training, focus, memory, and mood', 'Cognitive Health', '🧠', 'weekly', 'detailed', 'summary', 14, true),
('SCREEN_LIGHT_EXPOSURE', 'Light & Circadian', 'Monitor sunlight exposure and light timing', 'Cognitive Health', '☀️', 'weekly', 'detailed', 'summary', 15, true),
('SCREEN_WELLNESS', 'Wellness & Connection', 'Track outdoor time, social interaction, stress levels', 'Connection + Purpose', '🌿', 'weekly', 'detailed', 'summary', 16, true),
('SCREEN_BIOMETRICS', 'Biometrics', 'Track weight, body composition, blood pressure', 'Core Care', '⚖️', 'weekly', 'detailed', 'summary', 17, true),
('SCREEN_COMPLIANCE', 'Health Compliance', 'Track screenings, medications, and preventive care', 'Core Care', '🏥', 'weekly', 'detailed', 'summary', 18, true),
('SCREEN_SKINCARE', 'Skincare & Sun Protection', 'Track skincare routine and sunscreen application', 'Core Care', '🧴', 'weekly', 'detailed', 'summary', 19, true),
('SCREEN_SUBSTANCES', 'Substance Tracking', 'Monitor alcohol, cigarettes, and caffeine', 'Core Care', '🚭', 'weekly', 'detailed', 'summary', 20, true);


-- =====================================================
-- PART 2: Link Metrics to Screens
-- =====================================================

INSERT INTO display_screens_display_metrics
(display_screen, display_metric, visualization_type, section, position, is_primary, display_order)
VALUES
('SCREEN_SLEEP', 'DISP_AWAKE_DURATION', 'chart', 'main', 'full_width', True, 1),
('SCREEN_SLEEP', 'DISP_AWAKE_EPISODE_COUNT', 'chart', 'main', 'full_width', False, 2),
('SCREEN_SLEEP', 'DISP_AWAKE_PERCENTAGE', 'chart', 'main', 'full_width', False, 3),
('SCREEN_SLEEP', 'DISP_AWAKE_PERIOD_DURATION', 'chart', 'main', 'full_width', False, 4),
('SCREEN_SLEEP', 'DISP_CORE_PERCENTAGE', 'chart', 'main', 'full_width', False, 5),
('SCREEN_SLEEP', 'DISP_CORE_SLEEP_DURATION', 'chart', 'main', 'full_width', False, 6),
('SCREEN_SLEEP', 'DISP_CORE_SLEEP_PERIOD_DURATION', 'chart', 'main', 'full_width', False, 7),
('SCREEN_SLEEP', 'DISP_DEEP_PERCENTAGE', 'chart', 'main', 'full_width', False, 8),
('SCREEN_SLEEP', 'DISP_DEEP_SLEEP_CYCLE_COUNT', 'chart', 'main', 'full_width', False, 9),
('SCREEN_SLEEP', 'DISP_DEEP_SLEEP_DURATION', 'chart', 'main', 'full_width', False, 10),
('SCREEN_SLEEP', 'DISP_DEEP_SLEEP_PERIOD_DURATION', 'chart', 'main', 'full_width', False, 11),
('SCREEN_SLEEP', 'DISP_PERIOD_AWAKE_DURATION', 'chart', 'main', 'full_width', False, 12),
('SCREEN_SLEEP', 'DISP_PERIOD_CORE_SLEEP_DURATION', 'chart', 'main', 'full_width', False, 13),
('SCREEN_SLEEP', 'DISP_PERIOD_DEEP_SLEEP_DURATION', 'chart', 'main', 'full_width', False, 14),
('SCREEN_SLEEP', 'DISP_PERIOD_REM_SLEEP_DURATION', 'chart', 'main', 'full_width', False, 15),
('SCREEN_SLEEP', 'DISP_REM_PERCENTAGE', 'chart', 'main', 'full_width', False, 16),
('SCREEN_SLEEP', 'DISP_REM_SLEEP_CYCLE_COUNT_241', 'chart', 'main', 'full_width', False, 17),
('SCREEN_SLEEP', 'DISP_REM_SLEEP_CYCLE_COUNT', 'chart', 'main', 'full_width', False, 18),
('SCREEN_SLEEP', 'DISP_REM_SLEEP_DURATION', 'chart', 'main', 'full_width', False, 19),
('SCREEN_SLEEP', 'DISP_REM_SLEEP_PERIOD_DURATION', 'chart', 'main', 'full_width', False, 20),
('SCREEN_SLEEP', 'DISP_SLEEP_EFFICIENCY', 'chart', 'main', 'full_width', False, 21),
('SCREEN_SLEEP', 'DISP_SLEEP_ENVIRONMENT_SCORE', 'chart', 'main', 'full_width', False, 22),
('SCREEN_SLEEP', 'DISP_SLEEP_LATENCY', 'chart', 'main', 'full_width', False, 23),
('SCREEN_SLEEP', 'DISP_SLEEP_ROUTINE_ADHERENCE', 'chart', 'main', 'full_width', False, 24),
('SCREEN_SLEEP', 'DISP_SLEEP_SESSIONS', 'chart', 'main', 'full_width', False, 25),
('SCREEN_SLEEP', 'DISP_SLEEP_TIME_CONSISTENCY', 'chart', 'main', 'full_width', False, 26),
('SCREEN_SLEEP', 'DISP_TOTAL_SLEEP_DURATION', 'chart', 'main', 'full_width', False, 27),
('SCREEN_SLEEP', 'DISP_TOTAL_SLEEP_WINDOW', 'chart', 'main', 'full_width', False, 28),
('SCREEN_SLEEP', 'DISP_WAKE_TIME_CONSISTENCY', 'chart', 'main', 'full_width', False, 29),
('SCREEN_SLEEP', 'DISP_SLEEP_DURATION', 'chart', 'main', 'full_width', False, 30),
('SCREEN_CARDIO', 'DISP_ACTIVE_TIME', 'chart', 'main', 'full_width', True, 1),
('SCREEN_CARDIO', 'DISP_ACTIVE_TIME_SESSION', 'chart', 'main', 'full_width', False, 2),
('SCREEN_CARDIO', 'DISP_CALCULATED_ACTIVE_TIME', 'chart', 'main', 'full_width', False, 3),
('SCREEN_CARDIO', 'DISP_CARDIO_DURATION', 'chart', 'main', 'full_width', False, 4),
('SCREEN_CARDIO', 'DISP_CARDIO_SESSIONS', 'chart', 'main', 'full_width', False, 5),
('SCREEN_CARDIO', 'DISP_ZONE_2_CARDIO_DURATION', 'chart', 'main', 'full_width', False, 6),
('SCREEN_CARDIO', 'DISP_ZONE_2_CARDIO_SESSION', 'chart', 'main', 'full_width', False, 7),
('SCREEN_CARDIO', 'DISP_ZONE_2_CARDIO_SESSIONS', 'chart', 'main', 'full_width', False, 8),
('SCREEN_STRENGTH', 'DISP_STRENGTH_SESSIONS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_STRENGTH', 'DISP_STRENGTH_TRAINING_DURATION', 'chart', 'main', 'full_width', False, 2),
('SCREEN_STRENGTH', 'DISP_STRENGTH_TRAINING_SESSION', 'chart', 'main', 'full_width', False, 3),
('SCREEN_STRENGTH', 'DISP_STRENGTH_TRAINING_SESSIONS', 'chart', 'main', 'full_width', False, 4),
('SCREEN_HIIT', 'DISP_HIIT_DURATION', 'chart', 'main', 'full_width', True, 1),
('SCREEN_HIIT', 'DISP_HIIT_SESSION', 'chart', 'main', 'full_width', False, 2),
('SCREEN_HIIT', 'DISP_HIIT_SESSIONS', 'chart', 'main', 'full_width', False, 3),
('SCREEN_HIIT', 'DISP_MOBILITY_DURATION', 'chart', 'main', 'full_width', False, 4),
('SCREEN_HIIT', 'DISP_MOBILITY_SESSION', 'chart', 'main', 'full_width', False, 5),
('SCREEN_HIIT', 'DISP_MOBILITY_SESSIONS', 'chart', 'main', 'full_width', False, 6),
('SCREEN_ACTIVITY', 'DISP_WALKING_DURATION', 'chart', 'main', 'full_width', True, 1),
('SCREEN_ACTIVITY', 'DISP_POST_MEAL_ACTIVITY_DURATION', 'chart', 'main', 'full_width', False, 2),
('SCREEN_ACTIVITY', 'DISP_POST_MEAL_ACTIVITY_SESSIONS', 'chart', 'main', 'full_width', False, 3),
('SCREEN_ACTIVITY', 'DISP_POST_MEAL_ACTIVITY_SESSIONS_BREAKFAST', 'chart', 'main', 'full_width', False, 4),
('SCREEN_ACTIVITY', 'DISP_POST_MEAL_ACTIVITY_SESSIONS_DINNER', 'chart', 'main', 'full_width', False, 5),
('SCREEN_ACTIVITY', 'DISP_POST_MEAL_ACTIVITY_SESSIONS_LUNCH', 'chart', 'main', 'full_width', False, 6),
('SCREEN_ACTIVITY', 'DISP_SEDENTARY_PERIOD', 'chart', 'main', 'full_width', False, 7),
('SCREEN_ACTIVITY', 'DISP_SEDENTARY_SESSIONS', 'chart', 'main', 'full_width', False, 8),
('SCREEN_ACTIVITY', 'DISP_SEDENTARY_TIME', 'chart', 'main', 'full_width', False, 9),
('SCREEN_ACTIVITY', 'DISP_STEPS', 'chart', 'main', 'full_width', False, 10),
('SCREEN_ACTIVITY', 'DISP_WALKING_SESSIONS', 'chart', 'main', 'full_width', False, 11),
('SCREEN_PROTEIN', 'DISP_PLANTBASED_PROTEIN_GRAMS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_PROTEIN', 'DISP_PLANTBASED_PROTEIN_PERCENTAGE', 'chart', 'main', 'full_width', False, 2),
('SCREEN_PROTEIN', 'DISP_PROTEIN_GRAMS', 'chart', 'main', 'full_width', False, 3),
('SCREEN_PROTEIN', 'DISP_PROTEIN_PER_KILOGRAM_BODY_WEIGHT', 'chart', 'main', 'full_width', False, 4),
('SCREEN_PROTEIN', 'DISP_PROTEIN_SERVINGS', 'chart', 'main', 'full_width', False, 5),
('SCREEN_PROTEIN', 'DISP_PROTEIN_SERVINGS_BREAKFAST', 'chart', 'main', 'full_width', False, 6),
('SCREEN_PROTEIN', 'DISP_PROTEIN_SERVINGS_DINNER', 'chart', 'main', 'full_width', False, 7),
('SCREEN_PROTEIN', 'DISP_PROTEIN_SERVINGS_LUNCH', 'chart', 'main', 'full_width', False, 8),
('SCREEN_PROTEIN', 'DISP_PROTEIN_VARIETY', 'chart', 'main', 'full_width', False, 9),
('SCREEN_VEGETABLES', 'DISP_VEGETABLE_SERVINGS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_VEGETABLES', 'DISP_VEGETABLE_SERVINGS_BREAKFAST', 'chart', 'main', 'full_width', False, 2),
('SCREEN_VEGETABLES', 'DISP_VEGETABLE_SERVINGS_DINNER', 'chart', 'main', 'full_width', False, 3),
('SCREEN_VEGETABLES', 'DISP_VEGETABLE_SERVINGS_LUNCH', 'chart', 'main', 'full_width', False, 4),
('SCREEN_VEGETABLES', 'DISP_VEGETABLE_SOURCE_COUNT', 'chart', 'main', 'full_width', False, 5),
('SCREEN_VEGETABLES', 'DISP_VEGETABLE_SOURCES', 'chart', 'main', 'full_width', False, 6),
('SCREEN_VEGETABLES', 'DISP_VEGETABLE_VARIETY', 'chart', 'main', 'full_width', False, 7),
('SCREEN_FRUITS', 'DISP_FRUIT_SERVINGS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_FRUITS', 'DISP_FRUIT_SERVINGS_BREAKFAST', 'chart', 'main', 'full_width', False, 2),
('SCREEN_FRUITS', 'DISP_FRUIT_SERVINGS_DINNER', 'chart', 'main', 'full_width', False, 3),
('SCREEN_FRUITS', 'DISP_FRUIT_SERVINGS_LUNCH', 'chart', 'main', 'full_width', False, 4),
('SCREEN_FRUITS', 'DISP_FRUIT_SOURCE_COUNT', 'chart', 'main', 'full_width', False, 5),
('SCREEN_FRUITS', 'DISP_FRUIT_SOURCES', 'chart', 'main', 'full_width', False, 6),
('SCREEN_FRUITS', 'DISP_FRUIT_VARIETY', 'chart', 'main', 'full_width', False, 7),
('SCREEN_FIBER', 'DISP_FIBER_GRAMS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_FIBER', 'DISP_FIBER_SERVINGS', 'chart', 'main', 'full_width', False, 2),
('SCREEN_FIBER', 'DISP_FIBER_SERVINGS_BREAKFAST', 'chart', 'main', 'full_width', False, 3),
('SCREEN_FIBER', 'DISP_FIBER_SERVINGS_DINNER', 'chart', 'main', 'full_width', False, 4),
('SCREEN_FIBER', 'DISP_FIBER_SERVINGS_LUNCH', 'chart', 'main', 'full_width', False, 5),
('SCREEN_FIBER', 'DISP_FIBER_SOURCE_COUNT', 'chart', 'main', 'full_width', False, 6),
('SCREEN_FIBER', 'DISP_FIBER_SOURCE_VARIETY', 'chart', 'main', 'full_width', False, 7),
('SCREEN_FIBER', 'DISP_FIBER_SOURCES', 'chart', 'main', 'full_width', False, 8),
('SCREEN_FIBER', 'DISP_LEGUME_SERVINGS', 'chart', 'main', 'full_width', False, 9),
('SCREEN_FIBER', 'DISP_LEGUME_SERVINGS_BREAKFAST', 'chart', 'main', 'full_width', False, 10),
('SCREEN_FIBER', 'DISP_LEGUME_SERVINGS_DINNER', 'chart', 'main', 'full_width', False, 11),
('SCREEN_FIBER', 'DISP_LEGUME_SERVINGS_LUNCH', 'chart', 'main', 'full_width', False, 12),
('SCREEN_FIBER', 'DISP_LEGUME_SOURCE_COUNT', 'chart', 'main', 'full_width', False, 13),
('SCREEN_FIBER', 'DISP_LEGUME_SOURCES', 'chart', 'main', 'full_width', False, 14),
('SCREEN_FIBER', 'DISP_LEGUME_VARIETY', 'chart', 'main', 'full_width', False, 15),
('SCREEN_FIBER', 'DISP_WHOLE_GRAIN_SERVINGS', 'chart', 'main', 'full_width', False, 16),
('SCREEN_FIBER', 'DISP_WHOLE_GRAIN_SERVINGS_BREAKFAST', 'chart', 'main', 'full_width', False, 17),
('SCREEN_FIBER', 'DISP_WHOLE_GRAIN_SERVINGS_DINNER', 'chart', 'main', 'full_width', False, 18),
('SCREEN_FIBER', 'DISP_WHOLE_GRAIN_SERVINGS_LUNCH', 'chart', 'main', 'full_width', False, 19),
('SCREEN_FIBER', 'DISP_WHOLE_GRAIN_SOURCE_COUNT', 'chart', 'main', 'full_width', False, 20),
('SCREEN_FIBER', 'DISP_WHOLE_GRAIN_SOURCES', 'chart', 'main', 'full_width', False, 21),
('SCREEN_FIBER', 'DISP_WHOLE_GRAIN_VARIETY', 'chart', 'main', 'full_width', False, 22),
('SCREEN_HYDRATION', 'DISP_WATER_CONSUMPTION', 'chart', 'main', 'full_width', True, 1),
('SCREEN_MEAL_TIMING', 'DISP_EATING_WINDOW_DURATION', 'chart', 'main', 'full_width', True, 1),
('SCREEN_MEAL_TIMING', 'DISP_FIRST_MEAL_DELAY', 'chart', 'main', 'full_width', False, 2),
('SCREEN_MEAL_TIMING', 'DISP_FIRST_MEAL_TIME', 'chart', 'main', 'full_width', False, 3),
('SCREEN_MEAL_TIMING', 'DISP_LAST_LARGE_MEAL_TIME', 'chart', 'main', 'full_width', False, 4),
('SCREEN_MEAL_TIMING', 'DISP_LAST_MEAL_BUFFER', 'chart', 'main', 'full_width', False, 5),
('SCREEN_MEAL_TIMING', 'DISP_LAST_MEAL_TIME', 'chart', 'main', 'full_width', False, 6),
('SCREEN_NUTRITION_QUALITY', 'DISP_BODY_FAT_PERCENTAGE', 'chart', 'main', 'full_width', True, 1),
('SCREEN_NUTRITION_QUALITY', 'DISP_ADDED_SUGAR_CONSUMED', 'chart', 'main', 'full_width', False, 2),
('SCREEN_NUTRITION_QUALITY', 'DISP_ADDED_SUGAR_SERVINGS', 'chart', 'main', 'full_width', False, 3),
('SCREEN_NUTRITION_QUALITY', 'DISP_ADDED_SUGAR_SERVINGS_BREAKFAST', 'chart', 'main', 'full_width', False, 4),
('SCREEN_NUTRITION_QUALITY', 'DISP_ADDED_SUGAR_SERVINGS_DINNER', 'chart', 'main', 'full_width', False, 5),
('SCREEN_NUTRITION_QUALITY', 'DISP_ADDED_SUGAR_SERVINGS_LUNCH', 'chart', 'main', 'full_width', False, 6),
('SCREEN_NUTRITION_QUALITY', 'DISP_FAT_SOURCE_COUNT', 'chart', 'main', 'full_width', False, 7),
('SCREEN_NUTRITION_QUALITY', 'DISP_FAT_SOURCES', 'chart', 'main', 'full_width', False, 8),
('SCREEN_NUTRITION_QUALITY', 'DISP_FATTY_FISH_SERVINGS', 'chart', 'main', 'full_width', False, 9),
('SCREEN_NUTRITION_QUALITY', 'DISP_HEALTHY_FAT_RATIO', 'chart', 'main', 'full_width', False, 10),
('SCREEN_NUTRITION_QUALITY', 'DISP_HEALTHY_FAT_SWAPS', 'chart', 'main', 'full_width', False, 11),
('SCREEN_NUTRITION_QUALITY', 'DISP_HEALTHY_FAT_SWAPS_BREAKFAST', 'chart', 'main', 'full_width', False, 12),
('SCREEN_NUTRITION_QUALITY', 'DISP_HEALTHY_FAT_SWAPS_DINNER', 'chart', 'main', 'full_width', False, 13),
('SCREEN_NUTRITION_QUALITY', 'DISP_HEALTHY_FAT_SWAPS_LUNCH', 'chart', 'main', 'full_width', False, 14),
('SCREEN_NUTRITION_QUALITY', 'DISP_HEALTHY_FAT_USAGE', 'chart', 'main', 'full_width', False, 15),
('SCREEN_NUTRITION_QUALITY', 'DISP_MONOUNATURATED_FAT_G', 'chart', 'main', 'full_width', False, 16),
('SCREEN_NUTRITION_QUALITY', 'DISP_PLANT_BASED_MEAL', 'chart', 'main', 'full_width', False, 17),
('SCREEN_NUTRITION_QUALITY', 'DISP_PLANT_BASED_MEALS_BREAKFAST', 'chart', 'main', 'full_width', False, 18),
('SCREEN_NUTRITION_QUALITY', 'DISP_PLANT_BASED_MEALS_DINNER', 'chart', 'main', 'full_width', False, 19),
('SCREEN_NUTRITION_QUALITY', 'DISP_PLANT_BASED_MEALS_LUNCH', 'chart', 'main', 'full_width', False, 20),
('SCREEN_NUTRITION_QUALITY', 'DISP_POLYUNSATURATED_FAT_G', 'chart', 'main', 'full_width', False, 21),
('SCREEN_NUTRITION_QUALITY', 'DISP_PROCESSED_MEAT_SERVING', 'chart', 'main', 'full_width', False, 22),
('SCREEN_NUTRITION_QUALITY', 'DISP_SATURATED_FAT_G', 'chart', 'main', 'full_width', False, 23),
('SCREEN_NUTRITION_QUALITY', 'DISP_SATURATED_FAT_PERCENTAGE', 'chart', 'main', 'full_width', False, 24),
('SCREEN_NUTRITION_QUALITY', 'DISP_SATURATED_FAT_BREAKFAST', 'chart', 'main', 'full_width', False, 25),
('SCREEN_NUTRITION_QUALITY', 'DISP_SATURATED_FAT_DINNER', 'chart', 'main', 'full_width', False, 26),
('SCREEN_NUTRITION_QUALITY', 'DISP_SATURATED_FAT_LUNCH', 'chart', 'main', 'full_width', False, 27),
('SCREEN_NUTRITION_QUALITY', 'DISP_ULTRAPROCESSED_FOOD_SERVINGS', 'chart', 'main', 'full_width', False, 28),
('SCREEN_NUTRITION_QUALITY', 'DISP_ULTRAPROCESSED_FOOD_SERVINGS_BREAKFAST', 'chart', 'main', 'full_width', False, 29),
('SCREEN_NUTRITION_QUALITY', 'DISP_ULTRAPROCESSED_FOOD_SERVINGS_DINNER', 'chart', 'main', 'full_width', False, 30),
('SCREEN_NUTRITION_QUALITY', 'DISP_ULTRAPROCESSED_FOOD_SERVINGS_LUNCH', 'chart', 'main', 'full_width', False, 31),
('SCREEN_NUTRITION_QUALITY', 'DISP_UNHEALTHY_FAT_USAGE', 'chart', 'main', 'full_width', False, 32),
('SCREEN_NUTRITION_QUALITY', 'DISP_WHOLE_FOOD_MEALS', 'chart', 'main', 'full_width', False, 33),
('SCREEN_NUTRITION_QUALITY', 'DISP_WHOLE_FOOD_MEALS_BREAKFAST', 'chart', 'main', 'full_width', False, 34),
('SCREEN_NUTRITION_QUALITY', 'DISP_WHOLE_FOOD_MEALS_DINNER', 'chart', 'main', 'full_width', False, 35),
('SCREEN_NUTRITION_QUALITY', 'DISP_WHOLE_FOOD_MEALS_LUNCH', 'chart', 'main', 'full_width', False, 36),
('SCREEN_MINDFULNESS', 'DISP_MINDFULNESS_DURATION', 'chart', 'main', 'full_width', True, 1),
('SCREEN_MINDFULNESS', 'DISP_MINDFULNESS_SESSIONS', 'chart', 'main', 'full_width', False, 2),
('SCREEN_MINDFULNESS', 'DISP_BREATHWORK_AND_MINDFULNESS_DURATION', 'chart', 'main', 'full_width', False, 3),
('SCREEN_MINDFULNESS', 'DISP_BREATHWORK_AND_MINDFULNESS_SESSIONS', 'chart', 'main', 'full_width', False, 4),
('SCREEN_MINDFULNESS', 'DISP_BREATHWORK_DURATION', 'chart', 'main', 'full_width', False, 5),
('SCREEN_MINDFULNESS', 'DISP_BREATHWORK_SESSIONS', 'chart', 'main', 'full_width', False, 6),
('SCREEN_MINDFULNESS', 'DISP_MEDITATION_DURATION', 'chart', 'main', 'full_width', False, 7),
('SCREEN_MINDFULNESS', 'DISP_MEDITATION_SESSIONS', 'chart', 'main', 'full_width', False, 8),
('SCREEN_COGNITIVE', 'DISP_BRAIN_TRAINING_DURATION', 'chart', 'main', 'full_width', True, 1),
('SCREEN_COGNITIVE', 'DISP_BRAIN_TRAINING_SESSIONS', 'chart', 'main', 'full_width', False, 2),
('SCREEN_COGNITIVE', 'DISP_FOCUS_RATING', 'chart', 'main', 'full_width', False, 3),
('SCREEN_COGNITIVE', 'DISP_JOURNALING_SESSIONS', 'chart', 'main', 'full_width', False, 4),
('SCREEN_COGNITIVE', 'DISP_MEMORY_CLARITY_RATING', 'chart', 'main', 'full_width', False, 5),
('SCREEN_COGNITIVE', 'DISP_MOOD_RATING', 'chart', 'main', 'full_width', False, 6),
('SCREEN_LIGHT_EXPOSURE', 'DISP_EARLY_MORNING_LIGHT_EXPOSURE_DURATION', 'chart', 'main', 'full_width', True, 1),
('SCREEN_LIGHT_EXPOSURE', 'DISP_SUNLIGHT_EXPOSURE_DURATION', 'chart', 'main', 'full_width', False, 2),
('SCREEN_LIGHT_EXPOSURE', 'DISP_SUNLIGHT_EXPOSURE_SESSIONS', 'chart', 'main', 'full_width', False, 3),
('SCREEN_WELLNESS', 'DISP_GRATITUDE_SESSIONS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_WELLNESS', 'DISP_MORNING_OUTDOOR_TIME_DURATION', 'chart', 'main', 'full_width', False, 2),
('SCREEN_WELLNESS', 'DISP_OUTDOOR_TIME_DURATION', 'chart', 'main', 'full_width', False, 3),
('SCREEN_WELLNESS', 'DISP_OUTDOOR_TIME_SESSIONS', 'chart', 'main', 'full_width', False, 4),
('SCREEN_WELLNESS', 'DISP_SCREEN_TIME_DURATION', 'chart', 'main', 'full_width', False, 5),
('SCREEN_WELLNESS', 'DISP_SCREEN_TIME_SESSIONS', 'chart', 'main', 'full_width', False, 6),
('SCREEN_WELLNESS', 'DISP_SOCIAL_INTERACTION', 'chart', 'main', 'full_width', False, 7),
('SCREEN_WELLNESS', 'DISP_STRESS_LEVEL_RATING', 'chart', 'main', 'full_width', False, 8),
('SCREEN_BIOMETRICS', 'DISP_BMI_CALCULATED', 'chart', 'main', 'full_width', True, 1),
('SCREEN_BIOMETRICS', 'DISP_CURRENT_WEIGHT', 'chart', 'main', 'full_width', False, 2),
('SCREEN_BIOMETRICS', 'DISP_DIASTOLIC_BLOOD_PRESSURE', 'chart', 'main', 'full_width', False, 3),
('SCREEN_BIOMETRICS', 'DISP_HIP_TO_WAIST_RATIO', 'chart', 'main', 'full_width', False, 4),
('SCREEN_BIOMETRICS', 'DISP_SYSTOLIC_BLOOD_PRESSURE', 'chart', 'main', 'full_width', False, 5),
('SCREEN_COMPLIANCE', 'DISP_BREAST_MRI_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_COMPLIANCE', 'DISP_CERVICAL_SCREENING_COMPLIANCE_STATUS_164', 'chart', 'main', 'full_width', False, 2),
('SCREEN_COMPLIANCE', 'DISP_CERVICAL_SCREENING_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', False, 3),
('SCREEN_COMPLIANCE', 'DISP_COLONOSCOPY_COMPLIANCE_STATUS_158', 'chart', 'main', 'full_width', False, 4),
('SCREEN_COMPLIANCE', 'DISP_COLONOSCOPY_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', False, 5),
('SCREEN_COMPLIANCE', 'DISP_DENTAL_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', False, 6),
('SCREEN_COMPLIANCE', 'DISP_MAMMOGRAM_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', False, 7),
('SCREEN_COMPLIANCE', 'DISP_MAMMOGRAM_COMPLIANCE_STATUS_161', 'chart', 'main', 'full_width', False, 8),
('SCREEN_COMPLIANCE', 'DISP_MAMMOGRAM_COMPLIANCE_STATUS_160', 'chart', 'main', 'full_width', False, 9),
('SCREEN_COMPLIANCE', 'DISP_MEDICATION_ADHERENCE', 'chart', 'main', 'full_width', False, 10),
('SCREEN_COMPLIANCE', 'DISP_MONTHS_SINCE_LAST_DENTAL_EXAM', 'chart', 'main', 'full_width', False, 11),
('SCREEN_COMPLIANCE', 'DISP_MONTHS_SINCE_LAST_MAMMOGRAM', 'chart', 'main', 'full_width', False, 12),
('SCREEN_COMPLIANCE', 'DISP_PHYSICAL_EXAM_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', False, 13),
('SCREEN_COMPLIANCE', 'DISP_PSA_TEST_COMPLIANCE_STATUS_166', 'chart', 'main', 'full_width', False, 14),
('SCREEN_COMPLIANCE', 'DISP_PSA_TEST_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', False, 15),
('SCREEN_COMPLIANCE', 'DISP_SKIN_CHECK_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', False, 16),
('SCREEN_COMPLIANCE', 'DISP_SKIN_CHECK_COMPLIANCE_STATUS_155', 'chart', 'main', 'full_width', False, 17),
('SCREEN_COMPLIANCE', 'DISP_SUNSCREEN_COMPLIANCE_EVENTS', 'chart', 'main', 'full_width', False, 18),
('SCREEN_COMPLIANCE', 'DISP_SUNSCREEN_COMPLIANCE_RATE', 'chart', 'main', 'full_width', False, 19),
('SCREEN_COMPLIANCE', 'DISP_SUPPLEMENT_ADHERENCE', 'chart', 'main', 'full_width', False, 20),
('SCREEN_COMPLIANCE', 'DISP_VISION_CHECK_COMPLIANCE_STATUS', 'chart', 'main', 'full_width', False, 21),
('SCREEN_COMPLIANCE', 'DISP_YEARS_SINCE_LAST_COLONOSCOPY', 'chart', 'main', 'full_width', False, 22),
('SCREEN_COMPLIANCE', 'DISP_YEARS_SINCE_LAST_HPV_SCREENING', 'chart', 'main', 'full_width', False, 23),
('SCREEN_COMPLIANCE', 'DISP_YEARS_SINCE_LAST_PHYSICAL', 'chart', 'main', 'full_width', False, 24),
('SCREEN_SKINCARE', 'DISP_BRUSHING_SESSIONS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_SKINCARE', 'DISP_FLOSSING_SESSIONS', 'chart', 'main', 'full_width', False, 2),
('SCREEN_SKINCARE', 'DISP_MORNING_SUNSCREEN_APPLICATIONS', 'chart', 'main', 'full_width', False, 3),
('SCREEN_SKINCARE', 'DISP_SKINCARE_ROUTINE_ADHERENCE', 'chart', 'main', 'full_width', False, 4),
('SCREEN_SKINCARE', 'DISP_SUNSCREEN_APPLICATIONS', 'chart', 'main', 'full_width', False, 5),
('SCREEN_SUBSTANCES', 'DISP_ALCOHOLIC_DRINKS', 'chart', 'main', 'full_width', True, 1),
('SCREEN_SUBSTANCES', 'DISP_ALCOHOLIC_DRINKS_VS_BASELINE', 'chart', 'main', 'full_width', False, 2),
('SCREEN_SUBSTANCES', 'DISP_CIGARETTES', 'chart', 'main', 'full_width', False, 3),
('SCREEN_SUBSTANCES', 'DISP_CIGARETTES_VS_BASELINE', 'chart', 'main', 'full_width', False, 4),
('SCREEN_SUBSTANCES', 'DISP_LAST_CAFFEINE_CONSUMPTION_BUFFER', 'chart', 'main', 'full_width', False, 5),
('SCREEN_SUBSTANCES', 'DISP_LAST_CAFFEINE_CONSUMPTION_TIME', 'chart', 'main', 'full_width', False, 6),
('SCREEN_SUBSTANCES', 'DISP_CAFFEINE_CONSUMED', 'chart', 'main', 'full_width', False, 7),
('SCREEN_SUBSTANCES', 'DISP_CAFFEINE_SOURCE_COUNT', 'chart', 'main', 'full_width', False, 8),
('SCREEN_SUBSTANCES', 'DISP_CAFFEINE_SOURCES', 'chart', 'main', 'full_width', False, 9),
('SCREEN_SUBSTANCES', 'DISP_LAST_ALCOHOLIC_DRINK_TIME', 'chart', 'main', 'full_width', False, 10);


-- =====================================================
-- Summary
-- =====================================================

DO $$
DECLARE
  screen_count INT;
  link_count INT;
BEGIN
  SELECT COUNT(*) INTO screen_count FROM display_screens;
  SELECT COUNT(*) INTO link_count FROM display_screens_display_metrics;

  RAISE NOTICE '✅ Display Screens Created';
  RAISE NOTICE '';
  RAISE NOTICE 'Total screens: %', screen_count;
  RAISE NOTICE 'Total metric-screen links: %', link_count;
  RAISE NOTICE '';
  RAISE NOTICE 'Screens organized by pillar and category';
END $$;

COMMIT;
