-- =====================================================
-- Populate Missing Display Metric Aggregations
-- =====================================================
-- Auto-generated by generate_missing_display_metric_aggregations.py
-- =====================================================

BEGIN;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRAIN_TRAINING_DURATION', 'AGG_BRAIN_TRAINING_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRAIN_TRAINING_DURATION', 'AGG_BRAIN_TRAINING_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRAIN_TRAINING_DURATION', 'AGG_BRAIN_TRAINING_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRAIN_TRAINING_SESSIONS', 'AGG_BRAIN_TRAINING_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRAIN_TRAINING_SESSIONS', 'AGG_BRAIN_TRAINING_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRAIN_TRAINING_SESSIONS', 'AGG_BRAIN_TRAINING_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FOCUS_RATING', 'AGG_FOCUS_RATING', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FOCUS_RATING', 'AGG_FOCUS_RATING', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FOCUS_RATING', 'AGG_FOCUS_RATING', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_JOURNALING_SESSIONS', 'AGG_JOURNALING_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_JOURNALING_SESSIONS', 'AGG_JOURNALING_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_JOURNALING_SESSIONS', 'AGG_JOURNALING_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEMORY_RATING', 'AGG_MEMORY_CLARITY_RATING', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEMORY_RATING', 'AGG_MEMORY_CLARITY_RATING', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEMORY_RATING', 'AGG_MEMORY_CLARITY_RATING', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MOOD_RATING', 'AGG_MOOD_RATING', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MOOD_RATING', 'AGG_MOOD_RATING', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MOOD_RATING', 'AGG_MOOD_RATING', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_LIGHT_DURATION', 'AGG_EARLY_MORNING_LIGHT_EXPOSURE_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_LIGHT_DURATION', 'AGG_EARLY_MORNING_LIGHT_EXPOSURE_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_LIGHT_DURATION', 'AGG_EARLY_MORNING_LIGHT_EXPOSURE_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUNLIGHT_DURATION', 'AGG_SUNLIGHT_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUNLIGHT_DURATION', 'AGG_SUNLIGHT_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUNLIGHT_DURATION', 'AGG_SUNLIGHT_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_GRATITUDE_SESSIONS', 'AGG_GRATITUDE_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_GRATITUDE_SESSIONS', 'AGG_GRATITUDE_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_GRATITUDE_SESSIONS', 'AGG_GRATITUDE_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFULNESS_DURATION', 'AGG_MINDFULNESS_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFULNESS_DURATION', 'AGG_MINDFULNESS_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFULNESS_DURATION', 'AGG_MINDFULNESS_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFULNESS_SESSIONS', 'AGG_MINDFULNESS_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFULNESS_SESSIONS', 'AGG_MINDFULNESS_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFULNESS_SESSIONS', 'AGG_MINDFULNESS_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_OUTDOOR_DURATION', 'AGG_MORNING_OUTDOOR_TIME_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_OUTDOOR_DURATION', 'AGG_MORNING_OUTDOOR_TIME_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_OUTDOOR_DURATION', 'AGG_MORNING_OUTDOOR_TIME_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_OUTDOOR_DURATION', 'AGG_OUTDOOR_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_OUTDOOR_DURATION', 'AGG_OUTDOOR_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_OUTDOOR_DURATION', 'AGG_OUTDOOR_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SCREEN_TIME_DURATION', 'AGG_SCREEN_TIME_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SCREEN_TIME_DURATION', 'AGG_SCREEN_TIME_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SCREEN_TIME_DURATION', 'AGG_SCREEN_TIME_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SCREEN_TIME_SESSIONS', 'AGG_SCREEN_TIME_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SCREEN_TIME_SESSIONS', 'AGG_SCREEN_TIME_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SCREEN_TIME_SESSIONS', 'AGG_SCREEN_TIME_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SOCIAL_INTERACTION', 'AGG_SOCIAL_INTERACTION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SOCIAL_INTERACTION', 'AGG_SOCIAL_INTERACTION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SOCIAL_INTERACTION', 'AGG_SOCIAL_INTERACTION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_LEVEL', 'AGG_STRESS_LEVEL', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_LEVEL', 'AGG_STRESS_LEVEL', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_LEVEL', 'AGG_STRESS_LEVEL', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_MGMT_DURATION', 'AGG_STRESS_MANAGEMENT_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_MGMT_DURATION', 'AGG_STRESS_MANAGEMENT_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_MGMT_DURATION', 'AGG_STRESS_MANAGEMENT_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_AGE', 'AGG_AWAKE_PERCENTAGE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_AGE', 'AGG_AWAKE_PERCENTAGE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_AGE', 'AGG_AWAKE_PERCENTAGE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ALCOHOL_DRINKS', 'AGG_ALCOHOL_QUANTITY', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ALCOHOL_DRINKS', 'AGG_ALCOHOL_QUANTITY', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ALCOHOL_DRINKS', 'AGG_ALCOHOL_QUANTITY', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BMI', 'AGG_BMI', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BMI', 'AGG_BMI', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BMI', 'AGG_BMI', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BODY_FAT_PCT', 'AGG_BODY_FAT_PCT', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BODY_FAT_PCT', 'AGG_BODY_FAT_PCT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BODY_FAT_PCT', 'AGG_BODY_FAT_PCT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAST_MRI_COMPLIANCE', 'AGG_BREAST_MRI_COMPLIANCE_STATUS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAST_MRI_COMPLIANCE', 'AGG_BREAST_MRI_COMPLIANCE_STATUS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAST_MRI_COMPLIANCE', 'AGG_BREAST_MRI_COMPLIANCE_STATUS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRUSHING_SESSIONS', 'AGG_BRUSHING_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRUSHING_SESSIONS', 'AGG_BRUSHING_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BRUSHING_SESSIONS', 'AGG_BRUSHING_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CERVICAL_COMPLIANCE', 'AGG_CERVICAL_SCREENING_COMPLIANCE_STATUS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CERVICAL_COMPLIANCE', 'AGG_CERVICAL_SCREENING_COMPLIANCE_STATUS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CERVICAL_COMPLIANCE', 'AGG_CERVICAL_SCREENING_COMPLIANCE_STATUS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CIGARETTES', 'AGG_CIGARETTES', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CIGARETTES', 'AGG_CIGARETTES', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CIGARETTES', 'AGG_CIGARETTES', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CIGARETTES_VS_BASELINE', 'AGG_CIGARETTES_VS_BASELINE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CIGARETTES_VS_BASELINE', 'AGG_CIGARETTES_VS_BASELINE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CIGARETTES_VS_BASELINE', 'AGG_CIGARETTES_VS_BASELINE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_COLONOSCOPY_COMPLIANCE', 'AGG_COLONOSCOPY_COMPLIANCE_STATUS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_COLONOSCOPY_COMPLIANCE', 'AGG_COLONOSCOPY_COMPLIANCE_STATUS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_COLONOSCOPY_COMPLIANCE', 'AGG_COLONOSCOPY_COMPLIANCE_STATUS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DENTAL_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_DENTAL_EXAM', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DENTAL_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_DENTAL_EXAM', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DENTAL_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_DENTAL_EXAM', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DIGITAL_SHUTOFF', 'AGG_DIGITAL_SHUTOFF_BUFFER', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DIGITAL_SHUTOFF', 'AGG_DIGITAL_SHUTOFF_BUFFER', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DIGITAL_SHUTOFF', 'AGG_DIGITAL_SHUTOFF_BUFFER', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_EVENING_ROUTINE', 'AGG_EVENING_ROUTINE_ADHERENCE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_EVENING_ROUTINE', 'AGG_EVENING_ROUTINE_ADHERENCE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_EVENING_ROUTINE', 'AGG_EVENING_ROUTINE_ADHERENCE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FLOSSING_SESSIONS', 'AGG_FLOSSING_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FLOSSING_SESSIONS', 'AGG_FLOSSING_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FLOSSING_SESSIONS', 'AGG_FLOSSING_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEIGHT', 'AGG_HEIGHT', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEIGHT', 'AGG_HEIGHT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEIGHT', 'AGG_HEIGHT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MAMMOGRAM_COMPLIANCE', 'AGG_MAMMOGRAM_COMPLIANCE_STATUS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MAMMOGRAM_COMPLIANCE', 'AGG_MAMMOGRAM_COMPLIANCE_STATUS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MAMMOGRAM_COMPLIANCE', 'AGG_MAMMOGRAM_COMPLIANCE_STATUS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDICATION_ADHERENCE', 'AGG_MEDICATION_ADHERENCE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDICATION_ADHERENCE', 'AGG_MEDICATION_ADHERENCE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDICATION_ADHERENCE', 'AGG_MEDICATION_ADHERENCE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_SUNSCREEN', 'AGG_MORNING_SUNSCREEN_APPLICATIONS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_SUNSCREEN', 'AGG_MORNING_SUNSCREEN_APPLICATIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MORNING_SUNSCREEN', 'AGG_MORNING_SUNSCREEN_APPLICATIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PEPTIDE_ADHERENCE', 'AGG_PEPTIDE_ADHERENCE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PEPTIDE_ADHERENCE', 'AGG_PEPTIDE_ADHERENCE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PEPTIDE_ADHERENCE', 'AGG_PEPTIDE_ADHERENCE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PHYSICAL_COMPLIANCE', 'AGG_PHYSICAL_EXAM_COMPLIANCE_STATUS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PHYSICAL_COMPLIANCE', 'AGG_PHYSICAL_EXAM_COMPLIANCE_STATUS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PHYSICAL_COMPLIANCE', 'AGG_PHYSICAL_EXAM_COMPLIANCE_STATUS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PSA_COMPLIANCE', 'AGG_PSA_TEST_COMPLIANCE_STATUS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PSA_COMPLIANCE', 'AGG_PSA_TEST_COMPLIANCE_STATUS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PSA_COMPLIANCE', 'AGG_PSA_TEST_COMPLIANCE_STATUS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SKIN_CHECK_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_SKIN_CHECK', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SKIN_CHECK_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_SKIN_CHECK', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SKIN_CHECK_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_SKIN_CHECK', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SKINCARE_ROUTINE', 'AGG_SKINCARE_ROUTINE_ADHERENCE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SKINCARE_ROUTINE', 'AGG_SKINCARE_ROUTINE_ADHERENCE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SKINCARE_ROUTINE', 'AGG_SKINCARE_ROUTINE_ADHERENCE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUNSCREEN_APPLICATIONS', 'AGG_SUNSCREEN_APPLICATIONS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUNSCREEN_APPLICATIONS', 'AGG_SUNSCREEN_APPLICATIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUNSCREEN_APPLICATIONS', 'AGG_SUNSCREEN_APPLICATIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUPPLEMENT_ADHERENCE', 'AGG_SUPPLEMENT_ADHERENCE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUPPLEMENT_ADHERENCE', 'AGG_SUPPLEMENT_ADHERENCE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SUPPLEMENT_ADHERENCE', 'AGG_SUPPLEMENT_ADHERENCE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VISION_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_VISION_CHECK', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VISION_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_VISION_CHECK', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VISION_COMPLIANCE', 'AGG_MONTHS_SINCE_LAST_VISION_CHECK', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WEIGHT', 'AGG_WEIGHT', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WEIGHT', 'AGG_WEIGHT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WEIGHT', 'AGG_WEIGHT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ADDED_SUGAR_GRAMS', 'AGG_ADDED_SUGAR_CONSUMED', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ADDED_SUGAR_GRAMS', 'AGG_ADDED_SUGAR_CONSUMED', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ADDED_SUGAR_GRAMS', 'AGG_ADDED_SUGAR_CONSUMED', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAKFAST', 'AGG_BREAKFAST', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAKFAST', 'AGG_BREAKFAST', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAKFAST', 'AGG_BREAKFAST', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAKFAST_TOTAL_SERVINGS', 'AGG_BREAKFAST_TOTAL_SERVINGS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAKFAST_TOTAL_SERVINGS', 'AGG_BREAKFAST_TOTAL_SERVINGS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREAKFAST_TOTAL_SERVINGS', 'AGG_BREAKFAST_TOTAL_SERVINGS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CAFFEINE_CONSUMED', 'AGG_CAFFEINE_CONSUMED', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CAFFEINE_CONSUMED', 'AGG_CAFFEINE_CONSUMED', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CAFFEINE_CONSUMED', 'AGG_CAFFEINE_CONSUMED', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CAFFEINE_SOURCE_COUNT', 'AGG_CAFFEINE_SOURCE_COUNT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CAFFEINE_SOURCE_COUNT', 'AGG_CAFFEINE_SOURCE_COUNT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CAFFEINE_SOURCE_COUNT', 'AGG_CAFFEINE_SOURCE_COUNT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DINNER', 'AGG_DINNER', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DINNER', 'AGG_DINNER', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DINNER', 'AGG_DINNER', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DINNER_TOTAL_SERVINGS', 'AGG_DINNER_TOTAL_SERVINGS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DINNER_TOTAL_SERVINGS', 'AGG_DINNER_TOTAL_SERVINGS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DINNER_TOTAL_SERVINGS', 'AGG_DINNER_TOTAL_SERVINGS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_EATING_WINDOW', 'AGG_EATING_WINDOW_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_EATING_WINDOW', 'AGG_EATING_WINDOW_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_EATING_WINDOW', 'AGG_EATING_WINDOW_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FAT_SOURCE_COUNT', 'AGG_FAT_SOURCE_COUNT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FAT_SOURCE_COUNT', 'AGG_FAT_SOURCE_COUNT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FAT_SOURCE_COUNT', 'AGG_FAT_SOURCE_COUNT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FATTY_FISH_SERVINGS', 'AGG_FATTY_FISH_SERVINGS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FATTY_FISH_SERVINGS', 'AGG_FATTY_FISH_SERVINGS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FATTY_FISH_SERVINGS', 'AGG_FATTY_FISH_SERVINGS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIBER_SOURCE_COUNT', 'AGG_FIBER_SOURCE_COUNT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIBER_SOURCE_COUNT', 'AGG_FIBER_SOURCE_COUNT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIBER_SOURCE_COUNT', 'AGG_FIBER_SOURCE_COUNT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIRST_MEAL_DELAY', 'AGG_FIRST_MEAL_DELAY', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIRST_MEAL_DELAY', 'AGG_FIRST_MEAL_DELAY', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIRST_MEAL_DELAY', 'AGG_FIRST_MEAL_DELAY', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIRST_MEAL_TIME', 'AGG_FIRST_MEAL_TIME', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIRST_MEAL_TIME', 'AGG_FIRST_MEAL_TIME', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FIRST_MEAL_TIME', 'AGG_FIRST_MEAL_TIME', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FRUIT_SOURCE_COUNT', 'AGG_FRUIT_SOURCE_COUNT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FRUIT_SOURCE_COUNT', 'AGG_FRUIT_SOURCE_COUNT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_FRUIT_SOURCE_COUNT', 'AGG_FRUIT_SOURCE_COUNT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEALTHY_FAT_RATIO', 'AGG_HEALTHY_FAT_RATIO', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEALTHY_FAT_RATIO', 'AGG_HEALTHY_FAT_RATIO', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEALTHY_FAT_RATIO', 'AGG_HEALTHY_FAT_RATIO', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEALTHY_FAT_SWAPS_TIMING', 'AGG_HEALTHY_FAT_SWAPS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEALTHY_FAT_SWAPS_TIMING', 'AGG_HEALTHY_FAT_SWAPS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_HEALTHY_FAT_SWAPS_TIMING', 'AGG_HEALTHY_FAT_SWAPS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LARGE_MEALS_TIMING', 'AGG_LARGE_MEALS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LARGE_MEALS_TIMING', 'AGG_LARGE_MEALS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LARGE_MEALS_TIMING', 'AGG_LARGE_MEALS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_LARGE_MEAL_BUFFER', 'AGG_LAST_LARGE_MEAL_BUFFER', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_LARGE_MEAL_BUFFER', 'AGG_LAST_LARGE_MEAL_BUFFER', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_LARGE_MEAL_BUFFER', 'AGG_LAST_LARGE_MEAL_BUFFER', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_LARGE_MEAL_TIME', 'AGG_LAST_LARGE_MEAL_TIME', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_LARGE_MEAL_TIME', 'AGG_LAST_LARGE_MEAL_TIME', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_LARGE_MEAL_TIME', 'AGG_LAST_LARGE_MEAL_TIME', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_MEAL_BUFFER', 'AGG_LAST_MEAL_BUFFER', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_MEAL_BUFFER', 'AGG_LAST_MEAL_BUFFER', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_MEAL_BUFFER', 'AGG_LAST_MEAL_BUFFER', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_MEAL_TIME', 'AGG_LAST_MEAL_TIME', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_MEAL_TIME', 'AGG_LAST_MEAL_TIME', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_MEAL_TIME', 'AGG_LAST_MEAL_TIME', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LEGUME_SOURCE_COUNT', 'AGG_LEGUME_SOURCE_COUNT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LEGUME_SOURCE_COUNT', 'AGG_LEGUME_SOURCE_COUNT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LEGUME_SOURCE_COUNT', 'AGG_LEGUME_SOURCE_COUNT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LUNCH', 'AGG_LUNCH', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LUNCH', 'AGG_LUNCH', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LUNCH', 'AGG_LUNCH', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LUNCH_TOTAL_SERVINGS', 'AGG_LUNCH_TOTAL_SERVINGS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LUNCH_TOTAL_SERVINGS', 'AGG_LUNCH_TOTAL_SERVINGS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LUNCH_TOTAL_SERVINGS', 'AGG_LUNCH_TOTAL_SERVINGS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFUL_EATING_TIMING', 'AGG_MINDFUL_EATING', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFUL_EATING_TIMING', 'AGG_MINDFUL_EATING', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MINDFUL_EATING_TIMING', 'AGG_MINDFUL_EATING', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MUFA_GRAMS', 'AGG_SATURATED_FAT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MUFA_GRAMS', 'AGG_SATURATED_FAT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MUFA_GRAMS', 'AGG_SATURATED_FAT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PLANT_BASED_MEALS_TIMING', 'AGG_MEALS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PLANT_BASED_MEALS_TIMING', 'AGG_MEALS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PLANT_BASED_MEALS_TIMING', 'AGG_MEALS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PROCESSED_MEAT_TIMING', 'AGG_PROTEIN_TYPE_PROCESSED_MEAT', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PROCESSED_MEAT_TIMING', 'AGG_PROTEIN_TYPE_PROCESSED_MEAT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PROCESSED_MEAT_TIMING', 'AGG_PROTEIN_TYPE_PROCESSED_MEAT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PROTEIN_GRAMS', 'AGG_PROTEIN_GRAMS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PROTEIN_GRAMS', 'AGG_PROTEIN_GRAMS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PROTEIN_GRAMS', 'AGG_PROTEIN_GRAMS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PUFA_GRAMS', 'AGG_POLYUNSATURATED_FAT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PUFA_GRAMS', 'AGG_POLYUNSATURATED_FAT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_PUFA_GRAMS', 'AGG_POLYUNSATURATED_FAT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_RED_MEAT_SERVINGS', 'AGG_RED_MEAT_SERVINGS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_RED_MEAT_SERVINGS', 'AGG_RED_MEAT_SERVINGS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_RED_MEAT_SERVINGS', 'AGG_RED_MEAT_SERVINGS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SAT_FAT_GRAMS', 'AGG_POLYUNSATURATED_FAT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SAT_FAT_GRAMS', 'AGG_POLYUNSATURATED_FAT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SAT_FAT_GRAMS', 'AGG_POLYUNSATURATED_FAT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SAT_FAT_PCT', 'AGG_POLYUNSATURATED_FAT', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SAT_FAT_PCT', 'AGG_POLYUNSATURATED_FAT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SAT_FAT_PCT', 'AGG_POLYUNSATURATED_FAT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SATURATED_FAT_TIMING', 'AGG_SATURATED_FAT', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SATURATED_FAT_TIMING', 'AGG_SATURATED_FAT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SATURATED_FAT_TIMING', 'AGG_SATURATED_FAT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SEED_SERVINGS', 'AGG_SEED_SERVINGS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SEED_SERVINGS', 'AGG_SEED_SERVINGS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SEED_SERVINGS', 'AGG_SEED_SERVINGS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SNACKS', 'AGG_SNACKS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SNACKS', 'AGG_SNACKS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SNACKS', 'AGG_SNACKS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_TOTAL_MEALS', 'AGG_MEALS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_TOTAL_MEALS', 'AGG_MEALS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_TOTAL_MEALS', 'AGG_MEALS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VEGETABLE_SOURCE_COUNT', 'AGG_VEGETABLE_SOURCE_COUNT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VEGETABLE_SOURCE_COUNT', 'AGG_VEGETABLE_SOURCE_COUNT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VEGETABLE_SOURCE_COUNT', 'AGG_VEGETABLE_SOURCE_COUNT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WHOLE_FOOD_MEALS_TIMING', 'AGG_MEALS', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WHOLE_FOOD_MEALS_TIMING', 'AGG_MEALS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WHOLE_FOOD_MEALS_TIMING', 'AGG_MEALS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WHOLE_GRAIN_SOURCE_COUNT', 'AGG_WHOLE_GRAIN_SOURCE_COUNT', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WHOLE_GRAIN_SOURCE_COUNT', 'AGG_WHOLE_GRAIN_SOURCE_COUNT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WHOLE_GRAIN_SOURCE_COUNT', 'AGG_WHOLE_GRAIN_SOURCE_COUNT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ACTIVE_VS_CALCULATED', 'AGG_ACTIVE_VS_CALCULATED_TIME_DIFFERENCE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ACTIVE_VS_CALCULATED', 'AGG_ACTIVE_VS_CALCULATED_TIME_DIFFERENCE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_ACTIVE_VS_CALCULATED', 'AGG_ACTIVE_VS_CALCULATED_TIME_DIFFERENCE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CALCULATED_ACTIVE_TIME', 'AGG_CALCULATED_ACTIVE_TIME', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CALCULATED_ACTIVE_TIME', 'AGG_CALCULATED_ACTIVE_TIME', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CALCULATED_ACTIVE_TIME', 'AGG_CALCULATED_ACTIVE_TIME', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CALCULATED_EXERCISE_TIME', 'AGG_CALCULATED_EXERCISE_TIME', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CALCULATED_EXERCISE_TIME', 'AGG_CALCULATED_EXERCISE_TIME', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CALCULATED_EXERCISE_TIME', 'AGG_CALCULATED_EXERCISE_TIME', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CARDIO_DURATION', 'AGG_CARDIO_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CARDIO_DURATION', 'AGG_CARDIO_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CARDIO_DURATION', 'AGG_CARDIO_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_RESTING_HR', 'AGG_RESTING_HEART_RATE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_RESTING_HR', 'AGG_RESTING_HEART_RATE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_RESTING_HR', 'AGG_RESTING_HEART_RATE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VO2_MAX', 'AGG_VO2_MAX', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VO2_MAX', 'AGG_VO2_MAX', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_VO2_MAX', 'AGG_VO2_MAX', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WALKING_DURATION', 'AGG_WALKING_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WALKING_DURATION', 'AGG_WALKING_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WALKING_DURATION', 'AGG_WALKING_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WALKING_SESSIONS', 'AGG_WALKING_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WALKING_SESSIONS', 'AGG_WALKING_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WALKING_SESSIONS', 'AGG_WALKING_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_AWAKE_PCT', 'AGG_AWAKE_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_AWAKE_PCT', 'AGG_AWAKE_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_AWAKE_PCT', 'AGG_AWAKE_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CORE_PCT', 'AGG_CORE_SLEEP_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CORE_PCT', 'AGG_CORE_SLEEP_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_CORE_PCT', 'AGG_CORE_SLEEP_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DEEP_PCT', 'AGG_DEEP_SLEEP_CYCLE_COUNT', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DEEP_PCT', 'AGG_DEEP_SLEEP_CYCLE_COUNT', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_DEEP_PCT', 'AGG_DEEP_SLEEP_CYCLE_COUNT', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_DRINK_BUFFER', 'AGG_LAST_DRINK_BUFFER', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_DRINK_BUFFER', 'AGG_LAST_DRINK_BUFFER', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_LAST_DRINK_BUFFER', 'AGG_LAST_DRINK_BUFFER', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_REM_PCT', 'AGG_PERIOD_REM_SLEEP_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_REM_PCT', 'AGG_PERIOD_REM_SLEEP_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_REM_PCT', 'AGG_PERIOD_REM_SLEEP_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_EFFICIENCY', 'AGG_SLEEP_EFFICIENCY', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_EFFICIENCY', 'AGG_SLEEP_EFFICIENCY', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_EFFICIENCY', 'AGG_SLEEP_EFFICIENCY', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_ENVIRONMENT', 'AGG_SLEEP_ENVIRONMENT_SCORE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_ENVIRONMENT', 'AGG_SLEEP_ENVIRONMENT_SCORE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_ENVIRONMENT', 'AGG_SLEEP_ENVIRONMENT_SCORE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_LATENCY', 'AGG_SLEEP_LATENCY', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_LATENCY', 'AGG_SLEEP_LATENCY', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_LATENCY', 'AGG_SLEEP_LATENCY', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_ROUTINE', 'AGG_SLEEP_ROUTINE_ADHERENCE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_ROUTINE', 'AGG_SLEEP_ROUTINE_ADHERENCE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_ROUTINE', 'AGG_SLEEP_ROUTINE_ADHERENCE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_WINDOW', 'AGG_TOTAL_SLEEP_WINDOW', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_WINDOW', 'AGG_TOTAL_SLEEP_WINDOW', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_SLEEP_WINDOW', 'AGG_TOTAL_SLEEP_WINDOW', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_TIME_IN_BED', 'AGG_TIME_IN_BED_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_TIME_IN_BED', 'AGG_TIME_IN_BED_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_TIME_IN_BED', 'AGG_TIME_IN_BED_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WAKE_TIME_CONSISTENCY', 'AGG_WAKE_TIME_CONSISTENCY', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WAKE_TIME_CONSISTENCY', 'AGG_WAKE_TIME_CONSISTENCY', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WAKE_TIME_CONSISTENCY', 'AGG_WAKE_TIME_CONSISTENCY', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WEARABLE_USAGE', 'AGG_WEARABLE_USAGE', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WEARABLE_USAGE', 'AGG_WEARABLE_USAGE', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_WEARABLE_USAGE', 'AGG_WEARABLE_USAGE', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_DURATION', 'AGG_BREATHWORK_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_DURATION', 'AGG_BREATHWORK_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_DURATION', 'AGG_BREATHWORK_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_MINDFULNESS_DURATION', 'AGG_MINDFULNESS_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_MINDFULNESS_DURATION', 'AGG_MINDFULNESS_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_MINDFULNESS_DURATION', 'AGG_MINDFULNESS_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_MINDFULNESS_SESSIONS', 'AGG_MINDFULNESS_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_MINDFULNESS_SESSIONS', 'AGG_MINDFULNESS_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_MINDFULNESS_SESSIONS', 'AGG_MINDFULNESS_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_SESSIONS', 'AGG_BREATHWORK_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_SESSIONS', 'AGG_BREATHWORK_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_BREATHWORK_SESSIONS', 'AGG_BREATHWORK_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDITATION_DURATION', 'AGG_MEDITATION_DURATION', 'daily', 'AVG', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDITATION_DURATION', 'AGG_MEDITATION_DURATION', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDITATION_DURATION', 'AGG_MEDITATION_DURATION', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDITATION_SESSIONS', 'AGG_MEDITATION_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDITATION_SESSIONS', 'AGG_MEDITATION_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_MEDITATION_SESSIONS', 'AGG_MEDITATION_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_MGMT_SESSIONS', 'AGG_STRESS_MANAGEMENT_SESSIONS', 'daily', 'SUM', 1)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_MGMT_SESSIONS', 'AGG_STRESS_MANAGEMENT_SESSIONS', 'weekly', 'AVG', 2)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

INSERT INTO display_metrics_aggregations (metric_id, agg_metric_id, period_type, calculation_type_id, display_order)
VALUES ('DISP_STRESS_MGMT_SESSIONS', 'AGG_STRESS_MANAGEMENT_SESSIONS', 'monthly', 'AVG', 3)
ON CONFLICT (metric_id, agg_metric_id, period_type, calculation_type_id) DO NOTHING;

-- Verification
DO $$
DECLARE
  v_total_metrics INTEGER;
  v_metrics_with_aggs INTEGER;
  v_coverage_pct NUMERIC;
BEGIN
  SELECT COUNT(*) INTO v_total_metrics FROM display_metrics;
  SELECT COUNT(DISTINCT metric_id) INTO v_metrics_with_aggs FROM display_metrics_aggregations;
  v_coverage_pct := ROUND((v_metrics_with_aggs::NUMERIC / v_total_metrics) * 100, 1);
  
  RAISE NOTICE '';
  RAISE NOTICE '✅ Display Metric Aggregation Mapping Complete!';
  RAISE NOTICE '';
  RAISE NOTICE 'Summary:';
  RAISE NOTICE '  Total display metrics: %', v_total_metrics;
  RAISE NOTICE '  Metrics with aggregations: %', v_metrics_with_aggs;
  RAISE NOTICE '  Coverage: % percent', v_coverage_pct;
  RAISE NOTICE '';
END $$;

COMMIT;
