-- =====================================================
-- Map All Display Metrics to Screens
-- =====================================================
-- Generated: 2025-10-28
-- Maps all 202 display_metrics to primary/detail screens
-- =====================================================

BEGIN;

-- Clear existing mappings (if any)
DELETE FROM display_screens_primary_display_metrics;
DELETE FROM display_screens_detail_display_metrics;

-- =====================================================
-- PRIMARY SCREEN MAPPINGS (Summary Metrics)
-- =====================================================

INSERT INTO display_screens_primary_display_metrics
(primary_screen_id, metric_id, display_order, is_featured)
VALUES
('SCREEN_ACTIVITY_PRIMARY', 'DISP_CALCULATED_ACTIVE_TIME', 1, true),
('SCREEN_ACTIVITY_PRIMARY', 'DISP_CALCULATED_EXERCISE_TIME', 2, false),
('SCREEN_ACTIVITY_PRIMARY', 'DISP_SEDENTARY_PERIOD', 3, false),
('SCREEN_ACTIVITY_PRIMARY', 'DISP_SEDENTARY_SESSIONS', 4, false),
('SCREEN_ACTIVITY_PRIMARY', 'DISP_SEDENTARY_TIME', 5, false),
('SCREEN_ACTIVITY_PRIMARY', 'DISP_WALKING_DURATION', 6, false),
('SCREEN_ACTIVITY_PRIMARY', 'DISP_WALKING_SESSIONS', 7, false),
('SCREEN_ADDED_SUGAR_PRIMARY', 'DISP_ADDED_SUGAR_GRAMS', 1, true),
('SCREEN_ADDED_SUGAR_PRIMARY', 'DISP_ADDED_SUGAR_SERVINGS', 2, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_STRESS_MGMT_DURATION', 1, true),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_AGE', 2, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_BMI', 3, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_DM_1', 4, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_DIASTOLIC_BP', 5, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_DM_15', 6, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_HEIGHT', 7, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_DM_14', 8, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_DM_2', 9, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_SYSTOLIC_BP', 10, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_WEIGHT', 11, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_DM_13', 12, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_DM_12', 13, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_DM_4', 14, false),
('SCREEN_BIOMETRICS_PRIMARY', 'DISP_STRESS_MGMT_SESSIONS', 15, false),
('SCREEN_BRAIN_TRAINING_PRIMARY', 'DISP_BRAIN_TRAINING_DURATION', 1, true),
('SCREEN_BRAIN_TRAINING_PRIMARY', 'DISP_BRAIN_TRAINING_SESSIONS', 2, false),
('SCREEN_BREATHWORK_PRIMARY', 'DISP_BREATHWORK_DURATION', 1, true),
('SCREEN_BREATHWORK_PRIMARY', 'DISP_BREATHWORK_SESSIONS', 2, false),
('SCREEN_CARDIO_PRIMARY', 'DISP_CARDIO_DURATION', 1, true),
('SCREEN_CARDIO_PRIMARY', 'DISP_CARDIO_SESSIONS', 2, false),
('SCREEN_CARDIO_PRIMARY', 'DISP_ZONE_2_CARDIO_DURATION', 3, false),
('SCREEN_CARDIO_PRIMARY', 'DISP_ZONE_2_CARDIO_SESSION', 4, false),
('SCREEN_CARDIO_PRIMARY', 'DISP_ZONE_2_CARDIO_SESSIONS', 5, false),
('SCREEN_COGNITIVE_METRICS_PRIMARY', 'DISP_FOCUS_RATING', 1, true),
('SCREEN_COGNITIVE_METRICS_PRIMARY', 'DISP_MEMORY_RATING', 2, false),
('SCREEN_COGNITIVE_METRICS_PRIMARY', 'DISP_MOOD_RATING', 3, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_BREAST_MRI_COMPLIANCE', 1, true),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_CERVICAL_COMPLIANCE', 2, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_COLONOSCOPY_COMPLIANCE', 3, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_DENTAL_COMPLIANCE', 4, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_MAMMOGRAM_COMPLIANCE', 5, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_MONTHS_SINCE_BREAST_MRI', 6, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_MONTHS_SINCE_DENTAL', 7, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_MONTHS_SINCE_MAMMOGRAM', 8, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_MONTHS_SINCE_SKIN_CHECK', 9, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_MONTHS_SINCE_VISION', 10, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_PHYSICAL_COMPLIANCE', 11, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_PSA_COMPLIANCE', 12, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_SKIN_CHECK_COMPLIANCE', 13, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_VISION_COMPLIANCE', 14, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_YEARS_SINCE_COLONOSCOPY', 15, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_YEARS_SINCE_HPV', 16, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_YEARS_SINCE_PAP', 17, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_YEARS_SINCE_PHYSICAL', 18, false),
('SCREEN_COMPLIANCE_PRIMARY', 'DISP_YEARS_SINCE_PSA', 19, false),
('SCREEN_FIBER_PRIMARY', 'DISP_FIBER_SERVINGS', 1, true),
('SCREEN_FITNESS_METRICS_PRIMARY', 'DISP_CALORIES', 1, true),
('SCREEN_FITNESS_METRICS_PRIMARY', 'DISP_DM_7', 2, false),
('SCREEN_FITNESS_METRICS_PRIMARY', 'DISP_RESTING_HR', 3, false),
('SCREEN_FITNESS_METRICS_PRIMARY', 'DISP_VO2_MAX', 4, false),
('SCREEN_FITNESS_METRICS_PRIMARY', 'DISP_DM_8', 5, false),
('SCREEN_FRUITS_PRIMARY', 'DISP_FRUIT_SERVINGS', 1, true),
('SCREEN_GRATITUDE_PRIMARY', 'DISP_GRATITUDE_SESSIONS', 1, true),
('SCREEN_HEALTHY_FATS_PRIMARY', 'DISP_DM_3', 1, true),
('SCREEN_HEALTHY_FATS_PRIMARY', 'DISP_FATTY_FISH_SERVINGS', 2, false),
('SCREEN_HEALTHY_FATS_PRIMARY', 'DISP_HEALTHY_FAT_USAGE', 3, false),
('SCREEN_HEALTHY_FATS_PRIMARY', 'DISP_MUFA_GRAMS', 4, false),
('SCREEN_HEALTHY_FATS_PRIMARY', 'DISP_PUFA_GRAMS', 5, false),
('SCREEN_HEALTHY_FATS_PRIMARY', 'DISP_SAT_FAT_GRAMS', 6, false),
('SCREEN_HEALTHY_FATS_PRIMARY', 'DISP_DM_6', 7, false),
('SCREEN_HEALTHY_FATS_PRIMARY', 'DISP_DM_5', 8, false),
('SCREEN_HIIT_PRIMARY', 'DISP_HIIT_DURATION', 1, true),
('SCREEN_HIIT_PRIMARY', 'DISP_HIIT_SESSION', 2, false),
('SCREEN_HIIT_PRIMARY', 'DISP_HIIT_SESSIONS', 3, false),
('SCREEN_HYDRATION_PRIMARY', 'DISP_DM_11', 1, true),
('SCREEN_JOURNALING_PRIMARY', 'DISP_JOURNALING_SESSIONS', 1, true),
('SCREEN_LEGUMES_PRIMARY', 'DISP_LEGUME_SERVINGS', 1, true),
('SCREEN_LIGHT_EXPOSURE_PRIMARY', 'DISP_MORNING_LIGHT_DURATION', 1, true),
('SCREEN_LIGHT_EXPOSURE_PRIMARY', 'DISP_SUNLIGHT_DURATION', 2, false),
('SCREEN_LIGHT_EXPOSURE_PRIMARY', 'DISP_SUNLIGHT_SESSIONS', 3, false),
('SCREEN_MEAL_QUALITY_PRIMARY', 'DISP_PLANT_BASED_MEAL', 1, true),
('SCREEN_MEAL_QUALITY_PRIMARY', 'DISP_PROCESSED_MEAT_SERVING', 2, false),
('SCREEN_MEAL_QUALITY_PRIMARY', 'DISP_RED_MEAT_SERVINGS', 3, false),
('SCREEN_MEAL_QUALITY_PRIMARY', 'DISP_SEED_SERVINGS', 4, false),
('SCREEN_MEAL_TIMING_PRIMARY', 'DISP_EATING_WINDOW', 1, true),
('SCREEN_MEAL_TIMING_PRIMARY', 'DISP_TOTAL_MEALS', 2, false),
('SCREEN_MEDICATIONS_PRIMARY', 'DISP_MEDICATION_ADHERENCE', 1, true),
('SCREEN_MEDICATIONS_PRIMARY', 'DISP_PEPTIDE_ADHERENCE', 2, false),
('SCREEN_MEDICATIONS_PRIMARY', 'DISP_SUPPLEMENT_ADHERENCE', 3, false),
('SCREEN_MEDITATION_PRIMARY', 'DISP_MEDITATION_DURATION', 1, true),
('SCREEN_MEDITATION_PRIMARY', 'DISP_MEDITATION_SESSIONS', 2, false),
('SCREEN_MINDFULNESS_PRIMARY', 'DISP_MINDFULNESS_DURATION', 1, true),
('SCREEN_MINDFULNESS_PRIMARY', 'DISP_MINDFULNESS_SESSIONS', 2, false),
('SCREEN_MINDFULNESS_PRIMARY', 'DISP_BREATHWORK_MINDFULNESS_SESSIONS', 3, false),
('SCREEN_MINDFULNESS_PRIMARY', 'DISP_BREATHWORK_MINDFULNESS_DURATION', 4, false),
('SCREEN_MOBILITY_PRIMARY', 'DISP_MOBILITY_DURATION', 1, true),
('SCREEN_MOBILITY_PRIMARY', 'DISP_MOBILITY_SESSION', 2, false),
('SCREEN_MOBILITY_PRIMARY', 'DISP_MOBILITY_SESSIONS', 3, false),
('SCREEN_ORAL_HEALTH_PRIMARY', 'DISP_BRUSHING_SESSIONS', 1, true),
('SCREEN_ORAL_HEALTH_PRIMARY', 'DISP_FLOSSING_SESSIONS', 2, false),
('SCREEN_OUTDOOR_TIME_PRIMARY', 'DISP_MORNING_OUTDOOR_DURATION', 1, true),
('SCREEN_OUTDOOR_TIME_PRIMARY', 'DISP_OUTDOOR_DURATION', 2, false),
('SCREEN_OUTDOOR_TIME_PRIMARY', 'DISP_OUTDOOR_SESSIONS', 3, false),
('SCREEN_PROTEIN_PRIMARY', 'DISP_PLANT_PROTEIN_GRAMS', 1, true),
('SCREEN_PROTEIN_PRIMARY', 'DISP_PROTEIN_GRAMS', 2, false),
('SCREEN_PROTEIN_PRIMARY', 'DISP_PROTEIN_PER_KG', 3, false),
('SCREEN_ROUTINES_PRIMARY', 'DISP_DIGITAL_SHUTOFF', 1, true),
('SCREEN_ROUTINES_PRIMARY', 'DISP_EVENING_ROUTINE', 2, false),
('SCREEN_SCREEN_TIME_PRIMARY', 'DISP_SCREEN_TIME_DURATION', 1, true),
('SCREEN_SCREEN_TIME_PRIMARY', 'DISP_SCREEN_TIME_SESSIONS', 2, false),
('SCREEN_SKINCARE_PRIMARY', 'DISP_MORNING_SUNSCREEN', 1, true),
('SCREEN_SKINCARE_PRIMARY', 'DISP_SKINCARE_ROUTINE', 2, false),
('SCREEN_SKINCARE_PRIMARY', 'DISP_SUNSCREEN_APPLICATIONS', 3, false),
('SCREEN_SKINCARE_PRIMARY', 'DISP_SUNSCREEN_EVENTS', 4, false),
('SCREEN_SKINCARE_PRIMARY', 'DISP_SUNSCREEN_RATE', 5, false),
('SCREEN_SLEEP_ANALYSIS_PRIMARY', 'DISP_TOTAL_SLEEP_DURATION', 1, true),
('SCREEN_SLEEP_ANALYSIS_PRIMARY', 'DISP_DM_10', 2, false),
('SCREEN_SLEEP_CONSISTENCY_PRIMARY', 'DISP_WAKE_TIME_CONSISTENCY', 1, true),
('SCREEN_SLEEP_PRIMARY', 'DISP_SLEEP_DURATION', 1, true),
('SCREEN_SLEEP_PRIMARY', 'DISP_TIME_IN_BED', 2, false),
('SCREEN_SLEEP_QUALITY_PRIMARY', 'DISP_SLEEP_EFFICIENCY', 1, true),
('SCREEN_SLEEP_QUALITY_PRIMARY', 'DISP_SLEEP_ENVIRONMENT', 2, false),
('SCREEN_SLEEP_QUALITY_PRIMARY', 'DISP_SLEEP_LATENCY', 3, false),
('SCREEN_SLEEP_TIMING_PRIMARY', 'DISP_LAST_DRINK_BUFFER', 1, true),
('SCREEN_SLEEP_TIMING_PRIMARY', 'DISP_LAST_DRINK_TIME', 2, false),
('SCREEN_SLEEP_TIMING_PRIMARY', 'DISP_LAST_SCREEN_TIME', 3, false),
('SCREEN_SLEEP_TIMING_PRIMARY', 'DISP_SLEEP_ROUTINE', 4, false),
('SCREEN_SLEEP_TIMING_PRIMARY', 'DISP_SLEEP_WINDOW', 5, false),
('SCREEN_SLEEP_TIMING_PRIMARY', 'DISP_WEARABLE_USAGE', 6, false),
('SCREEN_SOCIAL_PRIMARY', 'DISP_SOCIAL_INTERACTION', 1, true),
('SCREEN_STEPS_PRIMARY', 'DISP_DM_9', 1, true),
('SCREEN_STRENGTH_PRIMARY', 'DISP_STRENGTH_SESSIONS', 1, true),
('SCREEN_STRENGTH_PRIMARY', 'DISP_STRENGTH_TRAINING_DURATION', 2, false),
('SCREEN_STRENGTH_PRIMARY', 'DISP_STRENGTH_TRAINING_SESSION', 3, false),
('SCREEN_STRENGTH_PRIMARY', 'DISP_STRENGTH_TRAINING_SESSIONS', 4, false),
('SCREEN_SUBSTANCES_PRIMARY', 'DISP_ALCOHOL_DRINKS', 1, true),
('SCREEN_SUBSTANCES_PRIMARY', 'DISP_CIGARETTES', 2, false),
('SCREEN_SUBSTANCES_PRIMARY', 'DISP_LAST_CAFFEINE_BUFFER', 3, false),
('SCREEN_SUBSTANCES_PRIMARY', 'DISP_LAST_CAFFEINE_TIME', 4, false),
('SCREEN_SUBSTANCES_PRIMARY', 'DISP_CAFFEINE_CONSUMED', 5, false),
('SCREEN_WELLNESS_PRIMARY', 'DISP_STRESS_LEVEL', 1, true);

-- =====================================================
-- DETAIL SCREEN MAPPINGS (Breakdown Metrics)
-- =====================================================

INSERT INTO display_screens_detail_display_metrics
(detail_screen_id, metric_id, display_order)
VALUES
('SCREEN_ACTIVITY_DETAIL', 'DISP_ACTIVE_VS_CALCULATED', 1),
('SCREEN_ADDED_SUGAR_DETAIL', 'DISP_ADDED_SUGAR_TIMING', 1),
('SCREEN_BIOMETRICS_DETAIL', 'DISP_WAIST_HIP_RATIO', 1),
('SCREEN_FIBER_DETAIL', 'DISP_FIBER_MEAL_TIMING', 1),
('SCREEN_FIBER_DETAIL', 'DISP_FIBER_SOURCE_COUNT', 2),
('SCREEN_FRUITS_DETAIL', 'DISP_FRUIT_SOURCE_COUNT', 1),
('SCREEN_FRUITS_DETAIL', 'DISP_FRUIT_MEAL_TIMING', 2),
('SCREEN_HEALTHY_FATS_DETAIL', 'DISP_BODY_FAT_PCT', 1),
('SCREEN_HEALTHY_FATS_DETAIL', 'DISP_FAT_SOURCE_COUNT', 2),
('SCREEN_HEALTHY_FATS_DETAIL', 'DISP_HEALTHY_FAT_RATIO', 3),
('SCREEN_HEALTHY_FATS_DETAIL', 'DISP_HEALTHY_FAT_SWAPS_TIMING', 4),
('SCREEN_HEALTHY_FATS_DETAIL', 'DISP_SAT_FAT_PCT', 5),
('SCREEN_HEALTHY_FATS_DETAIL', 'DISP_SATURATED_FAT_TIMING', 6),
('SCREEN_LEGUMES_DETAIL', 'DISP_LEGUME_SOURCE_COUNT', 1),
('SCREEN_LEGUMES_DETAIL', 'DISP_LEGUME_MEAL_TIMING', 2),
('SCREEN_MEAL_QUALITY_DETAIL', 'DISP_PLANT_BASED_MEALS_TIMING', 1),
('SCREEN_MEAL_QUALITY_DETAIL', 'DISP_PROCESSED_MEAT_TIMING', 2),
('SCREEN_MEAL_QUALITY_DETAIL', 'DISP_TAKEOUT_TIMING', 3),
('SCREEN_MEAL_QUALITY_DETAIL', 'DISP_WHOLE_FOOD_MEALS_TIMING', 4),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_BREAKFAST', 1),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_BREAKFAST_TOTAL_SERVINGS', 2),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_DINNER', 3),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_DINNER_TOTAL_SERVINGS', 4),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_FIRST_MEAL_DELAY', 5),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_FIRST_MEAL_TIME', 6),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_LARGE_MEALS_TIMING', 7),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_LAST_LARGE_MEAL_BUFFER', 8),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_LAST_LARGE_MEAL_TIME', 9),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_LAST_MEAL_BUFFER', 10),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_LAST_MEAL_TIME', 11),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_LUNCH', 12),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_LUNCH_TOTAL_SERVINGS', 13),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_MINDFUL_EATING_TIMING', 14),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_SNACKS', 15),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_EXERCISE_SNACK', 16),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_EXERCISE_SNACKS', 17),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_POST_MEAL_ACTIVITY_SESSIONS_BREAKFAST', 18),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_POST_MEAL_ACTIVITY_SESSIONS_DINNER', 19),
('SCREEN_MEAL_TIMING_DETAIL', 'DISP_POST_MEAL_ACTIVITY_SESSIONS_LUNCH', 20),
('SCREEN_NUTRITION_QUALITY_DETAIL', 'DISP_ULTRAPROCESSED_TIMING', 1),
('SCREEN_POST_MEAL_ACTIVITY_DETAIL', 'DISP_POST_MEAL_ACTIVITY_DURATION', 1),
('SCREEN_POST_MEAL_ACTIVITY_DETAIL', 'DISP_POST_MEAL_ACTIVITY_SESSIONS', 2),
('SCREEN_POST_MEAL_ACTIVITY_DETAIL', 'DISP_POST_MEAL_ACTIVITY_TIMING', 3),
('SCREEN_POST_MEAL_ACTIVITY_DETAIL', 'DISP_POST_MEAL_EXERCISE_TIMING', 4),
('SCREEN_PROTEIN_DETAIL', 'DISP_PLANT_PROTEIN_PCT', 1),
('SCREEN_PROTEIN_DETAIL', 'DISP_PROTEIN_MEAL_TIMING', 2),
('SCREEN_PROTEIN_DETAIL', 'DISP_PROTEIN_TYPE', 3),
('SCREEN_SLEEP_QUALITY_DETAIL', 'DISP_AWAKE_PCT', 1),
('SCREEN_SLEEP_QUALITY_DETAIL', 'DISP_AWAKE_EPISODES', 2),
('SCREEN_SLEEP_QUALITY_DETAIL', 'DISP_CORE_PCT', 3),
('SCREEN_SLEEP_QUALITY_DETAIL', 'DISP_DEEP_PCT', 4),
('SCREEN_SLEEP_QUALITY_DETAIL', 'DISP_DEEP_CYCLES', 5),
('SCREEN_SLEEP_QUALITY_DETAIL', 'DISP_REM_CYCLES', 6),
('SCREEN_SLEEP_QUALITY_DETAIL', 'DISP_REM_PCT', 7),
('SCREEN_SUBSTANCES_DETAIL', 'DISP_ALCOHOL_VS_BASELINE', 1),
('SCREEN_SUBSTANCES_DETAIL', 'DISP_CIGARETTES_VS_BASELINE', 2),
('SCREEN_SUBSTANCES_DETAIL', 'DISP_CAFFEINE_SOURCE_COUNT', 3),
('SCREEN_VEGETABLES_DETAIL', 'DISP_VEGETABLE_SOURCE_COUNT', 1),
('SCREEN_VEGETABLES_DETAIL', 'DISP_VEGETABLE_MEAL_TIMING', 2),
('SCREEN_WHOLE_GRAINS_DETAIL', 'DISP_WHOLE_GRAIN_SOURCE_COUNT', 1),
('SCREEN_WHOLE_GRAINS_DETAIL', 'DISP_WHOLE_GRAIN_MEAL_TIMING', 2);

-- =====================================================
-- VERIFICATION
-- =====================================================

DO $$
DECLARE
  primary_links INT;
  detail_links INT;
  total_metrics INT;
  unmapped INT;
BEGIN
  SELECT COUNT(*) INTO primary_links FROM display_screens_primary_display_metrics;
  SELECT COUNT(*) INTO detail_links FROM display_screens_detail_display_metrics;
  SELECT COUNT(*) INTO total_metrics FROM display_metrics WHERE is_active = true;

  -- Count metrics that aren't in either junction table
  SELECT COUNT(*) INTO unmapped
  FROM display_metrics dm
  WHERE dm.is_active = true
    AND NOT EXISTS (
      SELECT 1 FROM display_screens_primary_display_metrics
      WHERE metric_id = dm.metric_id
    )
    AND NOT EXISTS (
      SELECT 1 FROM display_screens_detail_display_metrics
      WHERE metric_id = dm.metric_id
    );

  RAISE NOTICE '✅ Display Metrics Mapped to Screens';
  RAISE NOTICE '';
  RAISE NOTICE 'Mappings:';
  RAISE NOTICE '  Primary screens: % metrics', primary_links;
  RAISE NOTICE '  Detail screens: % metrics', detail_links;
  RAISE NOTICE '  Total metrics: %', total_metrics;
  RAISE NOTICE '  Unmapped: % metrics', unmapped;
  RAISE NOTICE '';

  IF unmapped > 0 THEN
    RAISE WARNING '⚠️  % metrics are not mapped to any screen', unmapped;
  END IF;
END $$;

-- Show screens with metric counts
SELECT
  ds.name,
  ds.pillar,
  COUNT(DISTINCT pdm.metric_id) as primary_metrics,
  COUNT(DISTINCT ddm.metric_id) as detail_metrics,
  COUNT(DISTINCT pdm.metric_id) + COUNT(DISTINCT ddm.metric_id) as total_metrics
FROM display_screens ds
LEFT JOIN display_screens_primary dsp ON ds.screen_id = dsp.display_screen_id
LEFT JOIN display_screens_detail dsd ON ds.screen_id = dsd.display_screen_id
LEFT JOIN display_screens_primary_display_metrics pdm ON dsp.primary_screen_id = pdm.primary_screen_id
LEFT JOIN display_screens_detail_display_metrics ddm ON dsd.detail_screen_id = ddm.detail_screen_id
WHERE ds.is_active = true
GROUP BY ds.screen_id, ds.name, ds.pillar, ds.display_order
ORDER BY total_metrics DESC, ds.pillar, ds.display_order
LIMIT 20;

COMMIT;
